config/boot/entities.rb, lib/inferno/entities/message.rb, lib/inferno/entities/result.rb, suites/ips/document_operation.rb, suites/ips/summary_operation.rb
The load order change is to fix an issue that occurred when running the Docker image on a linux host.
=> Minor fixes for issues identified in connectathon

Gemfile, Gemfile.lock, client/src/components/LandingPage/__mocked_data__/mockData.ts, client/src/components/TestSuite/TestSuiteDetails/ResultIcon.tsx, client/src/components/TestSuite/__mocked_data__/mockData.ts, dev_suites/demo_ig_stu1/demo_suite.rb, dev_suites/smart/smart_suite.rb, lib/inferno.rb, lib/inferno/apps/web/controllers/test_runs/create.rb, lib/inferno/apps/web/controllers/test_sessions/create.rb, lib/inferno/apps/web/router.rb, lib/inferno/db/migrations/002_add_wait_support.rb, lib/inferno/dsl/request_storage.rb, lib/inferno/dsl/results.rb, lib/inferno/dsl/resume_test_route.rb, lib/inferno/dsl/runnable.rb, lib/inferno/entities/request.rb, lib/inferno/entities/result.rb, lib/inferno/entities/test_run.rb, lib/inferno/exceptions.rb, lib/inferno/repositories/repository.rb, lib/inferno/repositories/results.rb, lib/inferno/repositories/test_runs.rb, lib/inferno/test_runner.rb, spec/factories/test_run.rb, spec/inferno/dsl/runnable_spec.rb, spec/inferno/test_runner_spec.rb
This branch allows a test to return a `wait` result, which waits until an incoming request is received. When calling `wait`, an identifier must be provided to allow this test run to be identified in the incoming request. Routes can also be defined to resume test execution with `resume_test_route`, which takes an HTTP verb, a path, and a block which returns an identifier based on the incoming request.
The (placeholder) SMART suite included in this PR demonstrates this functionality. To see it in action, run the SMART tests, then navigate to `/custom/smart/launch?iss=abc`. That should redirect you back to the tests, where you can run the next test, which is able to access the details of the earlier incoming request.
It is also possible to just serve plain routes using any rack-compatible …
=> FI-1142: Serve custom endpoints

client/src/components/InputsModal/InputsModal.tsx, client/src/components/InputsModal/styles.tsx, client/src/components/TestSuite/TestSuiteDetails/TestListItem/RequestsList.tsx, client/src/components/TestSuite/TestSuiteDetails/TestListItem/styles.tsx
This PR makes it so really long url's don't cut off the rest of the request row. 
I also made the input labels bold and darker to differentiate it from the helper text
=> fix request url from pushing out buttons and change inputs label style

client/src/api/TestRunsApi.ts, client/src/components/InputsModal/InputTextArea.tsx, client/src/components/InputsModal/InputTextField.tsx, client/src/components/InputsModal/InputsModal.tsx, client/src/components/InputsModal/RequiredInputWarning.tsx, client/src/components/InputsModal/__tests__/InputModal.test.tsx, client/src/components/InputsModal/styles.tsx, client/src/components/TestSuite/TestSession.tsx, client/src/models/testSuiteModels.ts, dev_suites/dev_demo_ig_stu1/groups/demo_group.rb, lib/inferno/apps/web/controllers/test_runs/create.rb, lib/inferno/dsl/runnable.rb, lib/inferno/exceptions.rb, spec/inferno/dsl/runnable_spec.rb
This PR lets you specify inputs as optional. I decided to default inputs to required, and you have to specify that it's optional in the input definition. The client won't let you submit until you fill in something for all required fields. If you use postman to create a test run without all the required inputs, then you'll get back an error saying which inputs you're missing.
=> Fi 1311 add input require optional

dev_suites/dev_demo_ig_stu1/groups/demo_group.rb, lib/inferno/entities/test.rb, lib/inferno/test_runner.rb
This branch adds transient in-memory storage for passing data between tests during a single test run.
=> FI-1337: Add scratch

client/src/components/TestSuite/TestRunButton/TestRunButton.tsx, client/src/components/TestSuite/TestSession.tsx, client/src/components/TestSuite/TestSuiteDetails/TestGroupCard.tsx, client/src/components/TestSuite/TestSuiteDetails/TestGroupListItem.tsx, client/src/components/TestSuite/TestSuiteDetails/TestListItem/TestListItem.tsx, client/src/components/TestSuite/TestSuiteDetails/TestSuiteDetailsPanel.tsx, client/src/components/TestSuite/TestSuiteTree/TestGroupTreeItem.tsx, client/src/components/TestSuite/TestSuiteTree/TestSuiteTree.tsx, client/src/components/TestSuite/TestSuiteTree/TreeItemLabel.tsx, client/src/components/TestSuite/TestSuiteTree/__tests__/TestSuiteTree.test.tsx, client/src/models/testSuiteModels.ts, dev_suites/dev_demo_ig_stu1/demo_suite.rb, docs/swagger.yml, lib/inferno/apps/web/controllers/test_runs/create.rb, lib/inferno/apps/web/serializers/test.rb, lib/inferno/apps/web/serializers/test_group.rb, lib/inferno/dsl/runnable.rb, lib/inferno/entities/test_group.rb, lib/inferno/exceptions.rb, spec/inferno/dsl/runnable_spec.rb, spec/inferno/test_runner_spec.rb, spec/inferno/web/serializers/test_group_spec.rb, spec/inferno/web/serializers/test_spec.rb, spec/requests/test_runs_spec.rb
This PR adds the ability to mark test groups as run_as_group. This means that anything within that group cannot be run individually. You must run the highest level group that's marked as run_as_group.
=> Fi 1312 run as group

.env, lib/inferno/utils/middleware/request_logger.rb
The body of the response objects sent to the request logger is an array, so the code to not log the entire body was not working as intended. This fixes that and adds an environment variable that can be used to always log the entire body.
=> FI-1385: Fix request logging

lib/inferno/entities/request.rb, spec/inferno/entities/request_spec.rb
`fhir_client` relies on `rest-client`, which handles url-encoded request bodies differently from other types of request bodies. This branch adds code to correctly get a string for url-encoded request bodies (we have [similar functionality in legacy](https://github.com/onc-healthit/inferno-program/blob/main/lib/app/utils/logged_rest_client.rb#L80)).
=> FI-1403: Fix url-encoded request bodies

client/src/components/ActionModal/ActionModal.tsx, client/src/components/InputsModal/InputsModal.tsx, client/src/components/TestSuite/TestSession.tsx, dev_suites/dev_demo_ig_stu1/demo_suite.rb
If a test is in a 'wait' state, the user must perform action (I suppose theoretically you could create wait states where the tester isn't supposed to do anything and there is some other external thing that is supposed to go on, but i think this is the best way to describe this situation).  Previous to this PR, the 'wait' state was just shown as a message in the test result, and the user would have to know to find that result int the interface.  It needs to be more obvious.
This PR moves the wait message that tells the user what to do into a modal.  it is rendered as markdown, allowing a little bit of flexibilty in presentaion. The user cannot perform any other action in the interface (this is on purpose), except cancel the test.  Since we do not yet have test cancellation functionality, I …
=> Add modal when a test in a wait state.

.rubocop.yml, config/database.yml, dev_suites/dev_demo_ig_stu1/groups/demo_group.rb, lib/inferno/db/migrations/001_create_initial_structure.rb, lib/inferno/db/migrations/002_add_wait_support.rb, lib/inferno/db/migrations/003_update_session_data.rb, lib/inferno/db/migrations/004_add_request_results_table.rb, lib/inferno/db/migrations/005_add_updated_at_index_to_results.rb, lib/inferno/db/migrations/006_remove_unused_tables.rb, lib/inferno/db/schema.rb, spec/factories/request.rb, spec/factories/result.rb, spec/inferno/repositories/requests_spec.rb, spec/inferno/repositories/results_spec.rb
This branch updates inferno so that it works with postgres. SQLite is much more permissive, so migrations had to be updated in order to be compatible with postgres. Steps to test:
- run postgres:
```
docker run -p 5432:5432 -e POSTGRES_HOST_AUTH_METHOD=trust -e POSTGRES_DB=inferno_development postgres:14.1-alpine
```
- in `config/database.yml`, comment out the sqlite config and uncomment the postgres config
- add `gem 'pg'` to `Gemfile`
- `bundle install`
- `bundle exec bin/inferno migrate`
- `npm run dev` and everything should run normally.
You can also run the unit tests with postgres if you copy the postgres `development` config in `config/database.yml` to `test`.
=> FI-1398: Support postgres

lib/inferno/entities/result.rb
Omit should have a lower precedence than pass when rolling up test results.
=> Fix omit precedence

lib/inferno/dsl/assertions.rb, lib/inferno/dsl/fhir_client.rb, lib/inferno/dsl/http_client.rb, spec/inferno/dsl/fhir_client_spec.rb, spec/inferno/dsl/http_client_spec.rb
Added delete support to both http_client and fhir_client and added stream support to http_client using Faraday's on_data method. Created unit tests implemented for these new methods. Also added an extraneous assertion that kept coming up in Bulk Data and I thought could be useful elsewhere.
=> Delete and Stream Support

client/src/components/InputsModal/InputOAuthCredentials.tsx, client/src/components/InputsModal/InputsModal.tsx
After approving the oauth credential fronted PR, I realized that the behavior wasn't quite right.
No matter what, if the 'refresh token' field is filled in, 'token endpoint' and 'client id' MUST be filled in, because otherwise the refresh token is useless.  This applies if the oauth credential field is marked as optional or required.  Also, I made sure the 'required' tag shows up on these fields when the refresh token is filled in, because otherwise its not clear why you can't submit the form.
expires in / client secret never are required, because they may not be necessary to make the refresh token work.
=> Refine behavior of oauth required/optional fields.

dev_suites/dev_infrastructure_test/infrastructure_test.rb, docs/swagger.yml, lib/inferno/apps/web/serializers/test.rb, lib/inferno/apps/web/serializers/test_group.rb, lib/inferno/apps/web/serializers/test_suite.rb, lib/inferno/dsl/runnable.rb, spec/inferno/dsl/test_creation_spec.rb, spec/inferno/web/serializers/test_group_spec.rb, spec/inferno/web/serializers/test_spec.rb
Adds `input_instructions`, `short_title`, and `short description`.  Areas where this shows up in the legacy program interface in screenshots below.  Note that `short_title` wouldn't be in the top progress area because we do not have that in inferno-core, but it is still useful to have this option for our nav menus on the left / and potentially if we use breadcrumbs.
All are optional.  ~~`short_title `is used in place of `title `in some places.  If a `short_title` doesn't exist, `title` is used instead.  If `short_description` doesn't exist, the area would be blank in the interface, as `description` may be *very* long. It may be a little strange that these two similar concepts behave differently, but I modeled it after our legacy implementation for now.~~  Update: now there is no special …
=> Add input_instructions, short_title, short_descripton.

client/src/api/TestRunsApi.ts, client/src/components/ActionModal/ActionModal.tsx, client/src/components/TestSuite/TestRunProgressBar/TestRunProgressBar.tsx, client/src/components/TestSuite/TestSession.tsx, client/src/components/TestSuite/TestSuiteDetails/ResultIcon.tsx, client/src/components/TestSuite/TestSuiteTree/CondensedResultIcon.tsx, client/src/models/testSuiteModels.ts, dev_suites/dev_demo_ig_stu1/demo_suite.rb, lib/inferno/apps/web/controllers/test_runs/destroy.rb, lib/inferno/apps/web/router.rb, lib/inferno/entities/test_run.rb, lib/inferno/repositories/results.rb, lib/inferno/repositories/test_runs.rb, lib/inferno/test_runner.rb, spec/requests/test_runs_spec.rb
Note: I haven't added any unit tests for this functionality yet, but that is probably appropriate.
Note when reviewing: I believe the most critical use case for this for g10 is to get people unstuck from 'waiting' status.  If the case of cancelling any arbitrary tests that are running isn't quite perfect from a user experience, I don't think that is a huge deal at this point.
Functionally, when a test is 'cancelled', the test run is set to a 'cancelling' status. The test runner will finish the currently running test as normal, but then all of the rest of the tests will get a 'cancel' result.  And when completed, the test run will get changed to 'cancelled' status.
For tests in a 'wait' status, cancelling will start a new job, set the waiting test to 'cancel' result instead of 'pass', and …
=> Add ability to cancel test runs.

lib/inferno/dsl/configurable.rb, spec/inferno/dsl/configurable_spec.rb
This update is needed for the other SMART launches in the g10 suite (https://github.com/inferno-framework/g10-certification-test-kit/pull/11).
When a child is added to a group/suite, it inherits its parent's configuration. However, later updates to a parent's configuration were not being propagated down to its children, and this PR addresses that.
=> FI-1392: Apply config updates to children

client/src/components/InputsModal/InputsRadioGroup.tsx, client/src/components/TestSuite/TestSession.tsx, dev_suites/dev_demo_ig_stu1/groups/demo_group.rb
Removes the required label from radio button inputs and defaults selection to the first option value.
=> remove required label from radio button

dev_suites/dev_demo_ig_stu1/demo_suite.rb, lib/inferno/apps/web/controllers/test_runs/create.rb, lib/inferno/dsl/runnable.rb, spec/inferno/dsl/runnable_spec.rb
There was a bug with `missing_inputs` not properly handling renamed inputs. When checking whether an input was supplied by a prior output, the input's original name, rather than it's new name was being used. For instance:
```ruby
input :abcd, name: :defg
```
would check prior outputs for an output `abcd` when it should be checking for a prior output named `defg`.
=> FI-1438: Fix missing input issue

client/src/components/TestSuite/TestSuiteTree/CondensedResultIcon.tsx, client/src/components/TestSuite/TestSuiteTree/TestGroupTreeItem.tsx, client/src/components/TestSuite/TestSuiteTree/TestSuiteTree.tsx, client/src/components/TestSuite/TestSuiteTree/TreeItemLabel.tsx, client/src/components/TestSuite/TestSuiteTree/styles.tsx, client/src/components/TestSuite/styles.tsx, client/src/components/_common/TreeItem.tsx, dev_suites/ui_onc_program/additional_tests/onc_standalone_public_launch.rb, dev_suites/ui_onc_program/additional_tests/onc_visual_inspection.rb, dev_suites/ui_onc_program/additional_tests/smart_invalid_aud.rb, dev_suites/ui_onc_program/additional_tests/smart_invalid_launch.rb
The CSS is a little wonky here to make it line up in a way that I liked.  We can circle back and clean all that up though using standard units.  The biggest things are the removing the ability to drill into 'run_as_group' tests on the left bar, moving the status icon to the left, and putting in a placeholder 'not yet run' icon there too.  As long as you think this generally moves things forward I'd like to get this in by tomorrow.
BEFORE: 
AFTER:
=> Improve test sidebar

client/src/components/Header/Header.tsx, client/src/components/Header/__tests__/Header.test.tsx, client/src/components/TestSuite/TestRunButton/TestRunButton.tsx, client/src/components/TestSuite/TestSuiteDetails/TestGroupCard.tsx
I just added a 'New Session' button on the top right to make it obvious how to get out of this interface.  This doesn't look great, and should probably be more generic if there is more than one suite loaded, but I think its good to favor obvious functionality right now.
=> Add new session button.

client/src/components/InputsModal/InputsModal.tsx, dev_suites/dev_infrastructure_test/infrastructure_test.rb, spec/inferno/dsl/test_creation_spec.rb
Just renders the input instuctions using markdown because it helpful to have richtext when we need to describe things like required launch URIs.
The one mildly annoying thing is that now by default an extra `<p>` gets put in so the instructions are a bit more padded than necessary.  We can adjust how markdown is rendered in the future.
=> Make input instructions render in markdown.

client/src/components/TestSuite/TestRunButton/TestRunButton.tsx, client/src/components/TestSuite/TestSuiteDetails/TestGroupCard.tsx, client/src/components/TestSuite/TestSuiteDetails/TestGroupListItem.tsx, client/src/components/TestSuite/TestSuiteDetails/TestListItem/TestListItem.tsx
Fix a bug which prevented running individual tests from the UI. The `TestRunButton` had faulty logic which made it think that tests were test suites.
=> FI-1419: Make individual tests runnable

dev_suites/dev_infrastructure_test/infrastructure_test.rb, docs/swagger.yml, lib/inferno/apps/web/serializers/test_suite.rb, lib/inferno/entities/test_suite.rb, spec/inferno/entities/test_suite_spec.rb
So users can have something to reference when communicating an issue or request.
=> Add version to TestSuite

.env, lib/inferno/config/boot/db.rb
This branch makes inferno retry connecting to the database when a connection fails. This is needed to more easily support a database like postgres which may not have finished starting up when inferno tries to connect.
**NOTE:** Only the first commit is part of this PR (the changes to `db.rb` and `.env`). The other commit is there so that this functionality can be more easily tested.
To test, run:
```
docker-compose build
docker-compose run inferno bundle exec rake db:migrate
docker-compose up
```
When running `docker-compose up` you may see messages about not yet being able connect to the database, but it should retry and succeed eventually.
=> FI-1445: Retry db connections

client/src/components/TestSuite/TestSuiteDetails/TestSuiteDetailsPanel.tsx, client/src/components/TestSuite/TestSuiteDetails/TestSuiteMessages.tsx, client/src/models/testSuiteModels.ts, dev_suites/dev_demo_ig_stu1/demo_suite.rb, dev_suites/dev_infrastructure_test/infrastructure_test.rb, docs/swagger.yml, lib/inferno/apps/web/controllers/test_suites/check_configuration.rb, lib/inferno/apps/web/router.rb, lib/inferno/apps/web/serializers/test_suite.rb, lib/inferno/entities/test_suite.rb, spec/inferno/entities/test_suite_spec.rb, spec/inferno/web/serializers/test_suite_spec.rb, spec/requests/test_suites_spec.rb
This branch adds the ability to check configuration for a test suite, and add messages regarding the configuration. The UI for displaying these messages is very placeholder.
The demo suite has a warning and info message, and the infrastructure suite has an error message.
=> FI-1443: Add ability to check configuration for test suites

client/src/components/TestSuite/TestSuiteDetails/TestGroupListItem.tsx, client/src/components/TestSuite/TestSuiteDetails/TestListItem/TestListItem.tsx, client/src/components/TestSuite/TestSuiteTree/TestGroupTreeItem.tsx
Test items should load results as they come in (i.e. while accordions are open)
=> fix status update bug

.eslintrc.json, client/src/api/TestSessionApi.ts, client/src/components/Header/Header.tsx, client/src/components/PresetsModal/PresetsModal.tsx, client/src/components/TestSuite/TestSession.tsx, client/src/components/TestSuite/TestSessionWrapper.tsx, client/src/components/TestSuite/TestSuiteDetails/TestSuiteMessages.tsx, client/src/components/TestSuite/__tests__/TestSession.test.tsx, client/src/models/testSuiteModels.ts, config/presets/demo_preset.json, docs/swagger.yml, lib/inferno/apps/cli/main.rb, lib/inferno/apps/cli/suite.rb, lib/inferno/apps/cli/suite_input_template.rb, lib/inferno/apps/cli/suites.rb, lib/inferno/apps/web/controllers/test_sessions/create.rb, lib/inferno/apps/web/controllers/test_sessions/session_data/apply_preset.rb, lib/inferno/apps/web/router.rb, lib/inferno/apps/web/serializers/preset.rb, lib/inferno/apps/web/serializers/test_suite.rb, lib/inferno/config/boot/presets.rb, lib/inferno/dsl/runnable.rb, lib/inferno/entities/preset.rb, lib/inferno/entities/test_suite.rb, lib/inferno/repositories/in_memory_repository.rb, lib/inferno/repositories/presets.rb, lib/inferno/repositories/test_sessions.rb, lib/inferno/utils/preset_template_generator.rb, spec/inferno/web/serializers/test_suite_spec.rb, spec/requests/test_sessions_spec.rb
This branch adds initial support for presets.
```
bundle exec bin/inferno suites
bundle exec bin/inferno suite input_template SUITE_ID -f FILENAME.json
```
You can then fill in values in the preset and give it a title.
When you fetch suites via the json api, they include a list of their presets with the name & id so the UI can present them as options.
When creating a test session, you can add `?preset_id=PRESET_ID`, which will create session data for all of the inputs in the preset.
In a test session, if a suite has presets defined, there will be a button next to the `New Session` button that allows you to select a preset.
=> FI-1420: Support presets

client/src/components/TestSuite/TestSuiteDetails/TestSuiteReport.tsx, client/src/components/TestSuite/TestSuiteDetails/styles.tsx, client/src/components/TestSuite/styles.tsx
Add a report box to the top.  Note, if no version on the test kit exists, it just won't show that column.
Also reduced the side margins on the print view (probably could use some work but we can hold off until if/when we add more features to the report view, like including messages/http requests as an option for advanced users.
=> Add report summary box and reduce print margins.

.env, .env.development, README.md, client/src/components/TestSuite/TestSuiteDetails/TestGroupListItem.tsx
This branch fixes an error where inferno's base path was being added twice to group links in the UI.
**NOTE:** This branch also updates inferno's default base path so that these errors will be found more quickly in the future. By default inferno will be hosted at `localhost:4567/inferno`.
=> FI-1456: Fix navigation

client/src/components/TestSuite/TestRunButton/TestRunButton.tsx, client/src/components/TestSuite/TestSuiteDetails/TestGroupListItem.tsx, client/src/components/TestSuite/TestSuiteDetails/TestListItem/TestListItem.tsx, client/src/components/TestSuite/TestSuiteDetails/TestListItem/styles.tsx
All accordions should now be click to expand.
Any other additional actions (buttons, tab nav, etc.) should not modify the accordion, with the exception of badge icons -- these should only expand the panel on click (but not collapse).
Note that this should not work on the accordion content, i.e. clicking inside an expanded accordion should not collapse the accordion.
=> Accordion-clickable

lib/inferno/apps/web/index.html.erb, lib/inferno/config/application.rb
This will generate a new cache-busting token on bundle.js each time the service is restarted. This is a minimal solution that can probably be more comprehensive, to include webpack configuration updates so that all assets are purged and not just bundle.js. But in practice we hardly ever change the other assets so this should fix 95% of the problem right now.
=> FI-1426 Bust bundle.js cache.

lib/inferno/dsl/resume_test_route.rb
In our g10 tests, the user will almost never run the test from the group in which the wait/resume happens (exception is the 'other' launches), because it is embedded under a 'run_as_group' group.  In the current behavior, this causes the user to get stranded at a level in the UI that shouldn't ever be accessed for this particular set of tests.
See https://github.com/inferno-framework/inferno-core/issues/115
This update makes it so the user is redirected to the level in which they ran the test (could be suite, or group).  To try it out, run the 'Standalone Patient App' group in the g10 tests (see the `Gemfile` for how to get those tests showing up in `inferno-core`).  You should be redirected back to the `Standalone Patient App` group.  If you run all tests at the suite level, you should …
=> FI-1471 Resume Location

client/src/components/TestSuite/TestRunButton/TestRunButton.tsx, client/src/components/TestSuite/TestSuiteDetails/TestGroupCard.tsx, client/src/models/testSuiteModels.ts
We had logic in there to force the button to show up if at suite-level, because suites don't have "user_runnable" tagged to them (we probably should somehow allow suites decide if it makes sense to run everything in a suite or not all at once, but not in scope right now).  I updated the logic for that button so that it will show up as long as the runnable explicitly doesn't say "don't show the button", which works because the suite wouldn't say one way or another right now.  That way we don't need that function that checks if a runnable is a suite or not, which got broken in your other updates (it was looking for inputs to determine type, but now suites have inputs).  I deleted the function because it was the only place it was being used somehow...
I tested on the suite, groups that …
=> Fix suite-level run button.

dev_suites/dev_infrastructure_test/infrastructure_test.rb
GitHub Actions is intermittently failing one Ruby spec unrelated to PRs that are being opened, I believe because sometimes test files are loaded in different orders.  I noticed that we weren't explicitly calling `require_relative` for one group which was causing the issue.
```
An error occurred while loading spec_helper.
Failure/Error: raise Exceptions::ParentNotLoadedException.new(child_metadata[:class], superclass_id) unless superclass
Inferno::Exceptions::ParentNotLoadedException:
No TestGroup found with id 'failing_optional_group'
```
=> Require file to ensure it is loaded prior to test run.

client/src/components/ThemeProvider.tsx, client/src/styles/theme.tsx
* The move to v5 includes some temporary aliases it seems.
* The upgrade we did is fine but I believe these are the real and future names according to [theming docs](https://mui.com/customization/theming/)
This was exposed by using a babel direct import plugin in trying to shrink the bundle size.
=> Change material-ui imports.

client/src/components/InputsModal/InputsModal.tsx, client/src/components/InputsModal/__tests__/InputModal.test.tsx, client/src/components/TestSuite/TestRunButton/TestRunButton.tsx, client/src/components/TestSuite/TestSession.tsx, client/src/components/TestSuite/TestSuiteUtilities.tsx, client/src/models/testSuiteModels.ts, lib/inferno/apps/web/controllers/test_runs/create.rb, lib/inferno/apps/web/serializers/test.rb, lib/inferno/apps/web/serializers/test_group.rb, lib/inferno/apps/web/serializers/test_suite.rb, spec/inferno/web/serializers/test_group_spec.rb, spec/inferno/web/serializers/test_suite_spec.rb
This branch updates the ui to use the inputs as defined on the backend rather than doing its own calculations to determine which inputs to show far a runnable. Check with branch `fi-1478-update-for-input-handling-changes` on the g10 tertification tests.
=> FI-1478: UI updates

dev_suites/dev_demo_ig_stu1/demo_suite.rb, lib/inferno/dsl/input_output_handling.rb, spec/inferno/dsl/input_output_handling_spec.rb
This branch allows you to use `input_order` to specify the order of inputs in a runnable.
The order of inputs in `Group 3` in the demo suite was changed. So you can compare it to `Group 2` in the UI.
=> FI-1410: Input order

lib/inferno/dsl/input_output_handling.rb, lib/inferno/entities/test.rb, lib/inferno/utils/preset_template_generator.rb, spec/inferno/dsl/input_output_handling_spec.rb, spec/inferno/utils/preset_template_generator_spec.rb, spec/inferno/web/serializers/test_group_spec.rb, spec/inferno/web/serializers/test_spec.rb
If a runnable declared an input and renamed it, it would appear twice in `available_inputs` for that runnable.
=> FI-1500: Fix duplicated inputs

client/src/components/LandingPage/__mocked_data__/mockData.ts, client/src/components/TestSuite/TestRunButton/TestRunButton.tsx, client/src/components/TestSuite/TestSession.tsx, client/src/components/TestSuite/TestSuiteTree/__tests__/TestSuiteTree.test.tsx, client/src/components/TestSuite/TestSuiteUtilities.tsx, client/src/components/TestSuite/__mocked_data__/mockData.ts, client/src/components/_common/__mocked_data__/mockData.ts, client/src/models/testSuiteModels.ts
* change Runnable interfaces to types
* create a base type called Runnable (RunnableType is still needed)
* move all common properties to Runnable
* change outside code to use Runnable instead of `Test | TestGroup | TestSuite`
=> Refactor typescript model types

lib/inferno/dsl/fhir_validation.rb, lib/inferno/ext/fhir_models.rb, spec/inferno/dsl/assertions_spec.rb, spec/inferno/dsl/fhir_validation_spec.rb
This branch uses our existing workaround for including primitive extensions in FHIR models. This was raised as an issue for certification: https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/67
=> FI-1520: Include primitive extensions when validating

client/src/components/InputsModal/InputOAuthCredentials.tsx, client/src/components/InputsModal/InputTextArea.tsx, client/src/components/InputsModal/InputTextField.tsx
If an input is locked, we do not tell the user whether or not it is required.  While it is strange to have a locked field that you cannot do anything about tell you it is required, I think it is worse to not inform the user in any way why the 'Submit' button is disabled.  At least by enabling this, they can see that there is a field that they do not have access to change that is required (and hopefully there is information in the input instructions as to how to get that field filled out).
This is based on a question from a user that didn't know why they didn't have access to submitting the Single Patient API form in their configuration.
See Demo Suite 3.1.21 for an example.  Before:
After:
Note that this doesn't show what is really bad about not having required displayed, which is if …
=> Always show required label on form elements.

client/src/components/LandingPage/styles.tsx
On the landing page (`/suites` page for production), adjusted the suites display to center within the available space leftover from adding in a banner.
=> FI 1529: Center Suites Display

config/presets/us_core_v311_reference_server_preset.json, lib/inferno/entities/result.rb, spec/inferno/web/serializers/result_spec.rb
Fix an issue which causes an error when a result refers to a missing runnable. The runnable can be missing if it was removed or if its id changed. If the runnable is missing, `optional` is set to `true` on a result, since it can't be required if we don't even know what it's for.
How to test manually:
- `git checkout main`
- add `gem 'us_core_test_kit', '0.2.0'` to `Gemfile`
- `bundle`
- add `require 'us_core_test_kit'` to the top of `dev_suites/dev_demo_ig_stu1/demo_suite.rb`
- `npm run dev`
- run the Patient group
- stop inferno
- update the us core version to `0.2.1` in the `Gemfile`
- `bundle update us_core_test_kit`
- `npm run dev`
- reload your test session in the browser, and it should fail
- stop inferno
- `git stash`
- `git checkout handle-results-with-missing-runnables`
- `git …
=> FI-1532: Handle results with missing runnables

client/src/components/PresetsSelector/PresetsSelector.tsx
Sorts presets alphabetically, with `None` at the beginning of the list.
=> FI-1536-sort-presets

lib/inferno/dsl/request_storage.rb, spec/inferno/test_runner_spec.rb
This branch makes it so that if a named request can not be loaded, the test is skipped rather than generating a purple error.
=> FI-1538: Skip on missing request

client/src/components/App/App.tsx, client/src/components/App/__mocked_data__/mockData.ts, client/src/components/App/__tests__/App.test.tsx, client/src/store/app.ts, client/src/store/devtools.ts, package-lock.json, package.json
* introduce the library
* create a store (for App only for the moment)
* move the App component to use Zustand instead of local hooks
The value of reducing prop drilling isn't realized with this small
change but it will avoid merge conflicts.
=> Use Zustand for React state management

lib/inferno/apps/web/router.rb
This is not an ideal fix but I am not sure if we should spend the effort right now figuring out exactly why CodeSpaces is acting weird here.  I'd like this as an option for DevDays in a few weeks and we have a lot of high priority things to work on.
=> Force sending Content-Type on landing pages for GitHub Codespaces.

client/src/components/TestSuite/TestSuiteDetails/TestGroupListItem.tsx, client/src/components/TestSuite/TestSuiteDetails/styles.tsx
There is a spacing issue in Firefox in the current version that I was unable to determine an elegant fix for.
Before:
After:
It is ugly enough that I think its worth having a bit of a CSS workaround here. I spend an hour or so debugging and couldn't find the answer, and it just doesn't seem worthwhile to spend much more time on it.
Before approving, check in Chrome to make sure that this isn't a Firefox-only thing.
=> Fix minor spacing issue.

client/src/components/TestSuite/TestSuiteDetails/TestListItem/MessageType.tsx, client/src/components/TestSuite/TestSuiteDetails/TestListItem/MessagesList.tsx, client/src/components/TestSuite/TestSuiteDetails/TestListItem/ProblemBadge.tsx, client/src/components/TestSuite/TestSuiteDetails/TestListItem/TestListItem.tsx, client/src/components/TestSuite/TestSuiteDetails/TestListItem/__tests__/helper.test.ts, client/src/components/TestSuite/TestSuiteDetails/TestListItem/helper.ts, client/src/components/TestSuite/TestSuiteDetails/TestListItem/styles.tsx
* only show errors and warnings, don't count info messages
* add colors and icons
* groups and sort messages by type
* extract out a "ProblemBadge" component to represent a more focused badge
=> Change TestListItem error and warning messages to be more readable

lib/inferno/config/boot.rb, lib/inferno/config/boot/db.rb, spec/inferno/web/serializers/result_spec.rb, spec/support/factory_bot.rb
This is the result of `bundle update` which I normally do not like to do but I wanted to see what would happen since internally someone had a stdlib/ruby compat issue.
There's a breaking change on a patch level semver bump on factory_bot ❔that is surprising but is fixed in this PR.  In case we need to move up a version for other reasons, this might be a useful PR and did not want to just throw this away.
Here is the summary from bundle update, skipping things that did not change:
```
Using public_suffix 4.0.7 (was 4.0.6)
Using simplecov_json_formatter 0.1.4 (was 0.1.3)
Fetching parallel 1.22.1 (was 1.21.0)
Fetching regexp_parser 2.3.1 (was 2.2.0)
Using i18n 1.10.0 (was 1.9.1)
Using sidekiq 6.4.2 (was 6.4.1)
Fetching nokogiri 1.13.5 (x86_64-darwin) (was 1.13.4)
Fetching parser 3.1.2.0 (was …
```
=> Gem updates and factory_bot breaking change fix

client/src/components/App/App.tsx
Fetching everything from the store will cause unnecessary rerenders. Doing it this way will be a good example for the future.  Have to be careful about selectors in Redux too.
Additionally, not all this scope is needed but this is the easiest
to read.  `setTestSuites` is used on one location and could be moved into the first useEffect().  Until we get used to a global store,
this might be the most familiar way to do it for now.
=> Change usage of zustand store to be more precise

lib/inferno/dsl/runnable.rb
Makes the `selected_suite_options` argument of `children` optional.
Previously, `children` was a private attribute that took no arguments. This will allow code that used `children` in this way to continue to function properly.
e.g. This specialized g10 test filtering code:
https://github.com/onc-healthit/onc-certification-g10-test-kit/blob/63eac95deedf9d9ee6a9d5f9df8e32dde70f684f/lib/onc_certification_g10_test_kit/single_patient_api_group.rb#L86
1. Uncomment the g10 test kit from the Gemfile
2. Uncomment `require_relative` of the g10 test kit in `demo_suite.rb`
3. run bundle install and then `npm run dev`
The following error will be thrown without the change included in this PR:
```shell
/inferno-core/lib/inferno/dsl/runnable.rb:401:in `children': wrong number of arguments (given 0, …
```
=> Make `selected_suite_options` argument of `children` optional

README.md, client/src/components/Footer/Footer.tsx, client/src/components/Footer/styles.tsx, client/src/components/Header/Header.tsx, client/src/components/Header/__tests__/Header.test.tsx, client/src/components/Header/styles.tsx, client/src/components/LandingPage/LandingPage.tsx, client/src/components/TestSuite/ConfigMessagesDetails/ConfigMessagesDetailsPanel.tsx, client/src/components/TestSuite/TestSession.tsx, client/src/components/TestSuite/TestSessionWrapper.tsx, client/src/components/TestSuite/TestSuiteDetails/TestGroupCard.tsx, client/src/components/TestSuite/TestSuiteDetails/TestGroupListItem.tsx, client/src/components/TestSuite/TestSuiteDetails/TestListItem/MessageType.tsx, client/src/components/TestSuite/TestSuiteDetails/TestListItem/MessagesList.tsx, client/src/components/TestSuite/TestSuiteDetails/TestListItem/ProblemBadge.tsx, client/src/components/TestSuite/TestSuiteDetails/TestListItem/TabPanel.tsx, client/src/components/TestSuite/TestSuiteDetails/TestListItem/TestListItem.tsx, client/src/components/TestSuite/TestSuiteDetails/TestListItem/styles.tsx, client/src/components/TestSuite/TestSuiteDetails/TestSuiteReport.tsx, client/src/components/TestSuite/TestSuiteDetails/styles.tsx, client/src/components/TestSuite/TestSuiteTree/TestSuiteTree.tsx, client/src/components/TestSuite/__tests__/TestSession.test.tsx, client/src/components/TestSuite/styles.tsx, client/src/styles/theme.tsx
**Key changes**
- Collapse drawer if screen width is < 800px. Drawer should be accessed via logo button in header.
- Change error icon from `Cancel` to `Error`.
- Update tab header and test item icon colors to use accessible orange.
- Refactor `RequestsBadge` to use `ProblemBadge`.
- Change styling of `TestListItem` tabs object to a nested box -- accessibility colors.
- Several minor flex changes to handle overflow.
**Testing**
1. Run core.
2. Shrink window size -- all features should be legible, accessible, and otherwise work as normal, excepting those listed in **Known Issues/TODO**.
3. In browser dev tools, switch to responsive screen (or the device of your choice) -- all features should be legible, accessible, and otherwise work as normal, excepting those listed in **Known …
=> Updates for responsive screens (1)

docs/swagger.yml, lib/inferno/apps/web/controllers/test_sessions/create.rb, lib/inferno/apps/web/serializers/suite_option.rb, lib/inferno/apps/web/serializers/test_group.rb, lib/inferno/apps/web/serializers/test_session.rb, lib/inferno/apps/web/serializers/test_suite.rb, lib/inferno/db/migrations/007_add_suite_options.rb, lib/inferno/db/schema.rb, lib/inferno/dsl/runnable.rb, lib/inferno/dsl/suite_option.rb, lib/inferno/entities/test_group.rb, lib/inferno/entities/test_session.rb, lib/inferno/entities/test_suite.rb, lib/inferno/repositories/test_sessions.rb, lib/inferno/test_runner.rb, spec/inferno/dsl/runnable_spec.rb, spec/inferno/test_runner_spec.rb, spec/inferno/web/serializers/test_session_spec.rb, spec/inferno/web/serializers/test_suite_spec.rb, spec/requests/test_sessions_spec.rb
This branch adds support for suite options to the JSON API. Options defined in suites are serialized to the front end, and options can be chosen for a particular test session. When retrieving a test session, the included test suite will be filtered according to the selected suite options.
=> FI-1590: Suite options JSON API

client/src/api/TestSessionApi.ts, client/src/components/App/App.tsx, client/src/components/Header/Header.tsx, client/src/components/LandingPage/LandingPage.tsx, client/src/components/SuiteOptionsPage/SuiteOptionsPage.tsx, client/src/components/SuiteOptionsPage/index.ts, client/src/components/SuiteOptionsPage/styles.tsx, client/src/components/TestSuite/TestSessionWrapper.tsx, client/src/models/testSuiteModels.ts, dev_suites/dev_options_suite/options_suite.rb, lib/inferno/apps/web/controllers/test_sessions/create.rb, lib/inferno/apps/web/router.rb
This is primary intended to be functional (and not pretty), to enable the functionality within the interface to choose options to aid continued development on test suites that need this.  It will also help us understand if this workflow is good enough to start or if we need to alter our strategy here substantially.
We have an explicit ticket to 'make this better looking', and to clean up the code. So as long as this meets the goal of enabling further development on the options feature 🔥 **_without affecting suites that do not use options_** :fire:, then it should be good enough.
The Landing Page will look the same:
If (and only if) you choose a suite that has options, (such as the 'Options Suite'), you'll be presented with this additional screen (the lorem ipsum is in the description of …
=> FI-1608-options-ui Initial functional options UI

lib/inferno/dsl/input_output_handling.rb, lib/inferno/entities/test.rb, spec/inferno/dsl/input_output_handling_spec.rb
Currently, a group's inputs/outputs are added to their children when the children are added. If an input/output is added after a child has been added, it is not added to that child. This branch fixes that issue. The particular use case is adding an input to an imported group which will be used by one of the tests within that group through a configuration option.
```ruby
group from: :some_group do
input :abc
config(
options: {
a_proc: -> {  "I'm a string containing #{abc}" }
}
)
end
```
=> FI-1474: Apply inputs/outputs defined after creation to children

dev_suites/dev_options_suite/options_suite.rb, lib/inferno/apps/web/serializers/test_group.rb, lib/inferno/apps/web/serializers/test_suite.rb, spec/inferno/dsl/runnable_spec.rb, spec/inferno/test_runner_spec.rb, spec/inferno/web/serializers/test_session_spec.rb
The `TestGroup` serializer was not correctly filtering its children based on suite options, so top level groups would be filtered correctly in the suite, but groups/tests further down were not being filtered.
=> FI-1638: Fix option filtering in serializers

dev_suites/dev_infrastructure_test/serializer_test.rb, dev_suites/dev_options_suite/options_suite.rb, docs/swagger.yml, lib/inferno/apps/web/controllers/test_runs/create.rb, lib/inferno/apps/web/serializers/input.rb, lib/inferno/apps/web/serializers/test.rb, lib/inferno/apps/web/serializers/test_group.rb, lib/inferno/apps/web/serializers/test_suite.rb, lib/inferno/dsl/input_output_handling.rb, lib/inferno/entities/input.rb, spec/inferno/dsl/input_output_handling_spec.rb, spec/inferno/web/serializers/test_group_spec.rb, spec/inferno/web/serializers/test_spec.rb
This branch filters inputs based on selected suite options. This is needed to support multiple version of the SMART IG where different input behaviors are required for the different versions. For example, PKCE is optional in SMART v1, but required in SMART v2, so the input needs to be handled differently depending on which version is being used.
Also includes the tiny fix for #228
=> FI-1644: Input filtering

.env.development, config/presets/demo_preset.json.erb, config/presets/g10_certification_preset.json.erb, config/presets/smart_preset.json.erb, config/presets/us_core_preset.json.erb, config/presets/us_core_v311_reference_server_preset.json.erb, lib/inferno/config/boot/presets.rb, lib/inferno/repositories/presets.rb, spec/fixtures/simple_preset.json, spec/fixtures/simple_preset.json.erb, spec/inferno/repositories/presets_spec.rb
We were talking about deployment pains and right now I think the team is commenting out the equivalent of this during deploy.  Since what this URL represents is not hardcoded, can be any URL even for staging (or dev as we call it), it should not be hardcoded and should be in an ENV (named `REFERENCE_SERVER_URL` here).
I'm not quite sure on the `.env` templates and what should go in what.  Should there be an example in the readme?  Is `.env.development` enough?
We should also add `REFERENCE_SERVER_URL` to the deployment repo.
I wanted to test the init that happens in `lib/inferno/config/boot/presets.rb` but it seemed a bit myopic.  That code does get invoked during test.  So maybe something could be done there.  I did make a change to it (just for a simpler syntax) and normally I'd have a …
=> Unhardcode base url in preset JSON for deployment

lib/inferno/apps/web/controllers/test_sessions/create.rb
If you `POST http://localhost:4567/inferno/api/test_sessions?test_suite_id=demo` with no payload, recent updates make this call fail because it assumes the payload is valid JSON always.  This just checks to see if it is empty.
Leaving as-is would break our deployment g10 redirect (https://inferno.healthit.gov/onc-certification-g10-test-kit), and we'd have to update README.  No reason to not keep it backwards-compatible.
See #225
=> FI-1645 Allow empty payloads on session creation again.

client/src/components/TestSuite/TestSuiteDetails/TestListItem/RequestsList.tsx
A bug was introduced in https://github.com/inferno-framework/inferno-core/pull/230/ where a minor syntax update led to the request detail modal not being populated.
I originally reverted to the fuzzy equality to `null` because we know that worked properly in all cases, but then decided to change to strict equality to `undefined` in case the fuzzy equality was flagged by a linter (wouldn't want this to get reflagged and changed back).  I can't think of a reason why moving this to `undefined` would be problematic, and it seems to work.
I didn't see any other obvious problems that other update may have introduced, but worth a scan of the PR linked in the first sentence of this to double-check.
Before fix, in Demo suite run group 2.1, and look for a request, click on details, and you should …
=> Fi-1665 Request modal bug

docs/_config.yml
Confirmed that this works by running it locally.
=> Add ga to docs pages

client/src/components/LandingPage/LandingPage.tsx, client/src/components/SuiteOptionsPage/SuiteOptionsPage.tsx, client/src/components/TestSuite/TestSession.tsx, client/src/components/TestSuite/styles.tsx
Removes all the scrollbars spacers that show up in my Firefox installation.  This isn't just in the new options page -- this has been in the main interface also for some time.  Asking to merge into another PR that isn't quite in yet.
Perhaps just make sure that I didn't inadvertently break anything?  But seems to work properly for me now.
=> Fixes phantom scrollbar.

lib/inferno/apps/web/controllers/test_runs/create.rb, lib/inferno/apps/web/controllers/test_runs/show.rb, lib/inferno/apps/web/serializers/test_group.rb, lib/inferno/apps/web/serializers/test_run.rb, lib/inferno/apps/web/serializers/test_suite.rb, lib/inferno/entities/test_run.rb, spec/inferno/web/serializers/test_group_spec.rb, spec/inferno/web/serializers/test_suite_spec.rb
**Issue:** The denominator of the Progress Bar reflects the total number of tests within a runnable; instead, it should only show the number of tests available given the selected options. This results from `test_runs` not using/receiving `suite_options` to filter its `test_count`.
**Fix:** Passed `suite_options` in the serializer calls (_create.rb_ and _show.rb_) for `test_run`. Additionally, added `suite_option` filtering for `test_count` both `TestSuites` and `TestGroups` (separate from the issue, but relevant to the goal of the ticket).
=> FI-1646 Progress Bar Bug w/ Options

.github/workflows/js.yml, client/src/components/App/__tests__/App.test.tsx, client/src/components/InputsModal/__tests__/InputModal.test.tsx, client/src/components/RequestDetailModal/__tests__/CodeBlock.test.tsx, client/src/components/RequestDetailModal/__tests__/RequestDetailModal.test.tsx, client/src/components/TestSuite/ConfigMessagesDetails/ConfigMessagesDetailsPanel.tsx, client/src/components/TestSuite/TestSuiteDetails/TestListItem/TestListItem.tsx, client/src/components/TestSuite/TestSuiteTree/__tests__/TestSuiteTree.test.tsx, client/src/components/TestSuite/__tests__/TestSession.test.tsx, client/src/setupTests.ts, package-lock.json, package.json, tsconfig.json, vite.config.ts
The react-markdown plugin that will enable github flavored markdown
(which we want for table rendering to meet parity with the legacy app)
does not work with Jest because of ES Modules.
Vitest works with ES Modules and has less config and boilerplate than
Jest and babel.  We cannot move to Vite (the dev server and builder)
because of unknown issues (could be the target, could be our hanami setup)
but we **can** move to vitest all by itself.
Vitest is about 2x as fast on our app:
```
entire test suite: vitest:3.86s jest:7.39s
single test file:  vitest:2.13s jest:4.61s
```
The syntax is very similar to Jest, with only small modifications needed for
mocking App.tsx which is a bit of an oddball because it's the root
component.
I had to bump some eslint packages to current versions to get a …
=> Transition test runner to vitest

config/presets/g10_certification_preset.json.erb, lib/inferno/apps/web/controllers/test_runs/create.rb
`Runnable#available_inputs` is expensive, and it was being called repeatedly when creating a test run. When creating a test run for a large test suite with a large number of inputs (like the whole g10 suite with options), it would time out.
Follow the instructions in the `Gemfile` for testing with the g10 suite. On `main`, it will hang when trying to run the entire suite. On this branch it won't.
=> Fix test run creation performance

client/src/components/RequestDetailModal/__mocked_data__/mockData.ts, client/src/components/TestSuite/TestSuiteDetails/TestListItem/RequestsList.tsx, client/src/components/TestSuite/TestSuiteDetails/TestListItem/__tests__/RequestList.test.tsx, client/src/models/testSuiteModels.ts, docs/swagger.yml, lib/inferno/apps/web/serializers/request.rb, lib/inferno/apps/web/serializers/result.rb, spec/requests/results_spec.rb
We store an index for each request so that we can order them correctly, but that index was not being serialized to the front end. This branch adds the index to the request summary serializer and sorts the requests in the front end.
This is difficult to really test because it requires that multiple requests be made in the same millisecond. Unit tests demonstrate the functionality.
=> FI-1719: Fix request order

client/src/components/TestSuite/TestSession.tsx
The TestSession component has a left pane and a TestSuite right pane. The bug on main is that they both scroll together.  This is because a style is missing on this element `maxHeight`.  I believe this is happening because of the javascript template literal.  I saw inflection locally.  Essentially I built the gem off of main and saw the bug, then I changed to a static string and the bug was fixed. Then I changed this to use a function (essentially same behavior as the template literal) and the bug was still fixed.
This was surprising.  I don't know why you can't
```
`calc(100vh - 64px - 56px - ${bannerHeight}px)`
```
When bannerHeight is just a variable but it doesn't seem to work.
My guess is maybe this code is loaded before the DOM fires.  In that case having a binding function would …
=> Fix pane scrolling bug when developing a testkit locally

.env.development, lib/inferno/config/boot.rb
Inferno is loading `.env` files out of order, e.g. it loads `.env` before `.env.development`. The `dotenv` gem does not overwrite environment variables, so values set in `.env` would take precedence over those set in `.env.development`. This branch adds support for `.local` files and loads them [in the same order `dotenv-rails` would](https://github.com/bkeepers/dotenv#what-other-env-files-can-i-use) (which is what most people would expect). 
Unit tests should still pass. You should be able to run tests as usual. You should be able to change values in `.env` and have the values in `.env.development` take precedence.
=> FI-1732: Fix .env* load order

client/src/components/App/App.tsx, client/src/components/SuiteOptionsPage/SuiteOptionsPage.tsx
If the suite options description is long (scrollbar), the width of the container will resize to optimally use space. 
You may need to mock a description that is long for this. While the description is long, resizing the window should also resize the description container. 
If the description is short, no resizing is necessary. This should only occur on larger screens; small screens should behave as normal.
=> options-width

docker-compose.background.yml, lib/inferno/apps/cli/main.rb
Add a message to `inferno start` if foreman isn't installed.
`gem uninstall foreman`, then run `bin/inferno start`.
=> FI-1735: Check for foreman installation

Gemfile.lock, inferno_core.gemspec
Does not happen when executing the services individually but within foreman get:
```
uninitialized constant Dry::Core::ClassAttributes::IDENTITY (NameError)
```
The bundle was resolving 0.9.0 of dry-core which was unexpected to others. So, locking dry-core.
Run `./bin/inferno start`.  In my case, it resolved `0.9.0` which might not be true for your system.  Additionally, locking `dry-core 0.9.0` bumps many gems but throws this exception.
=> Lock dry-core to avoid foreman exception

client/src/components/TestSuite/TestSuiteDetails/TestListItem/RequestsList.tsx, client/src/components/TestSuite/TestSuiteDetails/TestListItem/TestListItem.tsx, client/src/components/TestSuite/TestSuiteDetails/TestListItem/TestRunDetail.tsx, client/src/components/TestSuite/TestSuiteDetails/TestListItem/__tests__/TestListItem.test.tsx
A useEffect that was concerned with setting the tab index when the tab was empty of content was conflicting with another function which would set the tab index to the clicked on "ProblemBadge".  In theory, the old useEffect should not have affected the badge clicking but it clearly is.
Changing from the hook that fires on a data dependency to one that fires on the accordian expansion click solves the problem.  I've added tests to cover the previous situations.
I did not move the TabProps interface out of TestRunDetail.  I think that's a good place for it but I am using the type in the parent element.
Run and or inspect the tests that are added in this PR.  ;)
You can manually test too if you want.  Find test messages that have a variety of states:
1. Click on a test message with a …
=> Fix UI bug where the TestListItem accordian would expand to the wrong tab

CHANGELOG.md, Gemfile.lock, lib/inferno/repositories/session_data.rb, lib/inferno/version.rb
There was a missing require in the session data repo.
If you run the [fi-1736-dev-improvements](https://github.com/inferno-framework/inferno-template/tree/fi-1736-dev-improvements) branch in the template repo, the tests will fail due to the missing require.
If you update the core version in the gemspec in that branch to `0.4.2.pre`, you should be able to run the tests.
=> Fix missing require

lib/inferno/dsl/runnable.rb
Define `.inspect` for runnables so that they meaningful display strings while developing/debugging.
Before:
```
[1] pry(main)> DemoIG_STU1::DemoSuite
=> DemoIG_STU1::DemoSuite
[2] pry(main)> DemoIG_STU1::DemoSuite.children
=> [#<Class:0x000000010eb8cf90>,
#<Class:0x000000010eb6d168>,
#<Class:0x000000010ea4fd58>,
#<Class:0x000000010e92ea28>,
#<Class:0x000000010e9252c0>,
#<Class:0x000000010e91dc78>,
#<Class:0x000000010e917738>,
#<Class:0x000000010e90cbd0>]
[3] pry(main)> DemoIG_STU1::DemoSuite.children.first.children
=> [#<Class:0x000000010eb86898>, #<Class:0x000000010eb7ec10>]
```
After:
```
[1] pry(main)> DemoIG_STU1::DemoSuite
=> #<DemoIG_STU1::DemoSuite @id="demo", @title="Demonstration Suite">
[2] pry(main)> DemoIG_STU1::DemoSuite.children
=> [#<Inferno::Entities::TestGroup …
```
=> FI-1783: Improve display for runnables

client/src/components/Header/Header.tsx, client/src/components/Header/__tests__/Header.test.tsx, client/src/components/Header/__tests__/HeaderSmall.test.tsx, client/src/components/Header/styles.tsx, client/src/components/TestSuite/TestSession.tsx, client/src/hooks/useTimeout.ts
* The link cancels polling so that we have no network memory leak
* I used react-router's Link so that relative links would work
* This caused some CSS styling to be lost so I moved the color etc into a homeLink rule
Start a test run, watch the status polling.  Click the home link.  The polling stops.  You navigate to the test suite selection screen.
=> FI-1481: Add home link to header on logo and suite title

docs/writing-tests/properties.md, docs/writing-tests/test-configuration.md, docs/writing-tests/test-inputs-outputs.md, lib/inferno/dsl/input_output_handling.rb
This branch adds documentation to various runnable properties which weren't yet documented.
=> FI-1866: Document runnable properties

docs/getting-started.md, docs/repo-layout-and-organization.md
Updated the instructions for running inferno to match the new way to develop test kits.
=> FI-1870: Update instructions for running inferno

lib/inferno/config/boot/suites.rb
When running in a test kit repo, the Test entity would not be loaded: `uninitialized constant Inferno::Test (NameError)`. This branch updates the suite loading to make sure that the Test entities are loaded prior to loading the suites.
=> FI-1879: Fix suite describe

docs/advanced-test-features/index.md, docs/advanced-test-features/serving-http-requests.md, docs/advanced-test-features/test-configuration.md, docs/advanced-test-features/waiting-for-requests.md, docs/available-test-kits.md, docs/deployment/index.md, docs/distributing-tests.md, docs/repo-layout-and-organization.md
This branch adds documentation for serving custom routes and using wait tests.
=> FI-1876: Document routes

client/src/api/RequestsApi.ts, client/src/api/TestRunsApi.ts, client/src/api/TestSessionApi.ts, client/src/api/TestSuitesApi.ts, client/src/api/VersionsApi.ts, client/src/components/App/App.tsx, client/src/components/LandingPage/LandingPage.tsx, client/src/components/SuiteOptionsPage/SuiteOptionsPage.tsx, client/src/components/TestSuite/TestSession.tsx, client/src/components/TestSuite/TestSessionWrapper.tsx, client/src/components/TestSuite/TestSuiteDetails/TestListItem/RequestsList.tsx
Navigating to a test suite options page via URL starts a new test session if there are no actual options.
Also makes console.logs console errors instead for future conversion to actual error handling.
http://localhost:4567/inferno/demo for local instances.
=> FI-1877: feature/empty-options

docs/advanced-test-features/configuration-checks.md, docs/advanced-test-features/scratch.md, docs/available-test-kits.md, docs/deployment/host.md, docs/getting-started.md, docs/writing-tests/assertions-and-results.md, docs/writing-tests/defining-tests.md, docs/writing-tests/fhir-validation.md, docs/writing-tests/making-requests.md, docs/writing-tests/test-inputs-outputs.md, lib/inferno/dsl/assertions.rb
This branch adds documentation for some small remaining features and fixes typos/cleans up remaining docs.
=> FI-1880: Misc. documentation

README.md, lib/inferno/dsl/assertions.rb, lib/inferno/dsl/configurable.rb, lib/inferno/dsl/fhir_client.rb, lib/inferno/dsl/fhir_validation.rb, lib/inferno/dsl/http_client.rb, lib/inferno/dsl/input_output_handling.rb, lib/inferno/dsl/request_storage.rb, lib/inferno/dsl/results.rb, lib/inferno/dsl/runnable.rb, lib/inferno/entities/request.rb, lib/inferno/entities/test.rb, lib/inferno/entities/test_group.rb, lib/inferno/entities/test_suite.rb
Minor updates to yard docs. Mainly marking methods I don't want to expose as private and marking methods whose return values should not be used as returning void.
Run `bin/docs` to regenerate the yard docs, then `open docs/docs/index.html` to see the changes.
=> FI-1883: Update yard docs

lib/inferno/ext/fhir_models.rb
When parsing fails, `from_json/xml` returns `nil`, so there was a nil safety issue in the FHIR models extension. See https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/397
=> FI-1885: Make fhir models extension nil safe

client/src/components/App/App.tsx, client/src/components/LandingPage/LandingPage.tsx, client/src/components/SuiteOptionsPage/SuiteOptionsPage.tsx, lib/inferno/apps/web/controllers/test_sessions/client_show.rb, lib/inferno/apps/web/router.rb, lib/inferno/entities/test_session.rb, spec/requests/client_requests_spec.rb
Update routes for sessions so they look like `BASE_PATH/:test_suite_id/:id` instead of `BASE_PATH/test_sessions/:id`. Old routes redirect to new routes.
Start sessions for the various suites and they should work. Replace the suite id in the url with `test_sessions` and you should be redirected to the original url.
=> FI-1881: Improve session routes

client/src/components/TestSuite/TestSession.tsx, client/src/components/TestSuite/TestSuiteDetails/TestListItem/ProblemBadge.tsx, client/src/components/TestSuite/TestSuiteDetails/TestListItem/TestListItem.tsx, client/src/components/TestSuite/TestSuiteDetails/TestListItem/TestRunDetail.tsx, client/src/components/TestSuite/TestSuiteTree/TestSuiteTree.tsx, client/src/components/TestSuite/TestSuiteTree/styles.tsx, client/src/components/TestSuite/styles.tsx
Clicking on the request or messages icon will now also change the selected test list item tab. Also adds an a11y fix for tree view.
Open a test list item with requests and messages, clicking the icons should change the open tab.
=> FI-1907: Change tab on icon click

docs/getting-started.md, lib/inferno/apps/cli/main.rb
Adds a `--watch` flag to `inferno start` that uses [rerun](https://github.com/alexch/rerun) to wrap the existing command that runs Inferno.  This is a pretty simple solution compared to a much more complex 'hot-reload' type functionality.  However, it saves test writers the need to do several commands to stop and restart every time a file changes and has the exact same result as that method of reloading Inferno.
I have it reload on the default `rerun` watch targets, which is almost all file types that we deal with, but not quite everything.  It won't restart when the Gemfile is changed, for example.  It also doesn't affect the `services`... it might make sense to add `--watch` to services when the IG `package.tgz` is updated, but that solution may look a little different than this and …
=> FI-1927 inferno start --watch command

lib/inferno/utils/preset_processor.rb, spec/inferno/utils/preset_processor_spec.rb
This branch prevents an exception when a preset contains an unknown input (see #337). A warning will be displayed for unknown inputs:
```
WARN -- : Unknown input patient_idxx in preset demo_preset
```
In addition to the unit test, you can add a bad input to a preset and see the warning in the logs.
=> FI-1939: Handle unknown inputs in preset

README.md
For developers that want to start at the repository (vs. documentation pages),  I think it would be good to add a little bit more orientation content to the inferno-core repo.
=> Update README to provide more context.

docs/getting-started.md
Just adding information on setting up the validator to the getting started for test writers docs.
=> FI-1945: Move template docs to core

lib/inferno/dsl/assertions.rb, spec/inferno/dsl/assertions_spec.rb
Use a different error message when no profile is given to avoid the error message looking like: `Resource does not conform to the profile:`
=> FI-1899: Fix validation error message when no profile is given

client/src/components/LandingPage/LandingPage.tsx, client/src/components/LandingPage/styles.tsx, client/src/components/SuiteOptionsPage/SuiteOptionsPage.tsx, client/src/components/SuiteOptionsPage/styles.tsx
Removes scrolling overflow in favor of automatic sizing.
Shrink browser height, selection card should not scroll.
=> FI-1975: fix flex model

lib/inferno/dsl/fhir_client.rb
This change fixes this header call syntax in the yard docs. It was wrong because the curly braces are interpreted as a block rather than a Hash.
=> FI-1978: Fix headers call syntax in yard docs

docs/api-docs/index.html
Fixes a bug where accessing the API without any query params would prevent the page from rendering
Spin up an API docs instance and navigate to:
http://127.0.0.1:4000/inferno-core/api-docs/
Page should render where it didn't before.
=> FI-2001: Make API link params optional

package-lock.json
Update packages
Run `npm audit --omit=dev`, should be 0 warnings
=> FI-1997: Security update

lib/inferno/entities/test_suite.rb
Log error and warning level config messages whenever configuration is checked.
Use a test kit which does configuration checks, and deliberately set your environment up to fail at least one of those checks (e.g. run the g(10) test kit without the validator running). Check the logs and you should see the same errors and warnings that are shown in the UI.
=> FI-1854: Log error and warning level config messages

client/src/components/TestSuite/TestRunProgressBar/TestRunProgressBar.tsx
Adds an extra check for test run status. If status is done, bar is marked as complete and auto-closes.
Same as https://github.com/inferno-framework/inferno-core/pull/371
=> FI-2042: Unstick progress bar when test run is complete

docs/writing-tests/making-requests.md, lib/inferno/dsl/fhir_client.rb, spec/inferno/dsl/fhir_client_spec.rb
New FHIR interactions in the Inferno DSL based on https://www.hl7.org/fhir/http.html#3.2.0:
- Instance: `vread`, `update`, `patch`, `history`
- Type: `history`
- System: `history`, `search`
I did **not** include conditional `create`, `update`, `patch`, and `delete`, because those are currently trial use.
This should not include any breaking changes to the DSL. All interactions listed above are new methods in the DSL except for `search` (type level search already existed).
There's a fair amount of repetitive tests in `fhir_client_spec.rb`. Most DSL methods have a set of separate tests defined to ensure each of:
- The method returns `Inferno::Entities::Request`
- The request is added to the request list
- The optional client parameter is honored
- Token refresh happens when necessary
- TCP …
=> FI-1821: Add a handful of operations to the FHIR DSL

client/src/components/Footer/Footer.tsx, client/src/components/InputsModal/InputOAuthCredentials.tsx, client/src/components/InputsModal/InputsModal.tsx
JSON string parsing and type handling was throwing errors in the input fields for OAuth, particularly when switching between field inputs to serial inputs. This should no longer occur.
1. Before, editing JSON inputs where an OAuth input was present would cause snackbar errors to appear indicating the JSON could not be parsed. This should be fixed.
2. Before, editing the OAuth fields in the JSON input and then switching back to field inputs would throw an uncaught JSON parse error. This should be fixed. Making changes and switching between inputs should be error free.
These can be tested in the Demonstration Suite.
=> FI-2040: Fix JSON parse error for OAuth inputs

codecov.yml
Adds config file for codecov
TBD
=> FI-2003: Add codecov.yml

client/src/components/InputsModal/InputsModal.tsx, client/src/components/InputsModal/styles.tsx, client/src/components/RequestDetailModal/CodeBlock.tsx, client/src/components/RequestDetailModal/styles.tsx
Fixes input dialog horizontal overflow issues: markdown scrolling in descriptions, JSON/YAML newlines and autowrapping, horizontal scrollbars
Test on g(10) Multi-Patient Auth -- run tests and in the inputs, horizontal scrollbar should no longer appear. Switching to YAML should also no longer break lines unnecessarily.
=> FI-2053: Fix inputs dialog overflow

client/src/components/InputsModal/InputCheckboxGroup.tsx, client/src/components/InputsModal/InputOAuthCredentials.tsx, client/src/components/InputsModal/InputRadioGroup.tsx, client/src/components/InputsModal/InputTextArea.tsx, client/src/components/InputsModal/InputTextField.tsx, client/src/components/InputsModal/InputsModal.tsx, codecov.yml
While editing inputs in the dialog, clicking outside the dialog should no longer automatically close the modal.
=> FI-2038: Prevent modal close on edit

client/src/components/App/App.tsx, client/src/components/Header/Header.tsx, client/src/components/RequestDetailModal/RequestDetailModal.tsx, client/src/components/TestSuite/TestSuiteDetails/ResultIcon.tsx, client/src/components/TestSuite/TestSuiteDetails/TestGroupListItem/TestGroupListItem.tsx, client/src/components/TestSuite/TestSuiteDetails/TestListItem/RequestList.tsx, client/src/components/TestSuite/TestSuiteDetails/TestListItem/TestListItem.tsx, package-lock.json, package.json
- Added tooltips to all icons without text except in report view
- Made all such icons focusable
- Updated snackbar styles
Are there places where additional tooltip support could be added? Places where tooltip indicators would be helpful?
- Report view has custom pointer behavior that prevents tooltips on hover, they are still accessible via keyboard tab through
=> FI-2094: Improve tooltip a11y

lib/inferno/dsl/fhir_validation.rb, lib/inferno/exceptions.rb, spec/inferno/dsl/fhir_validation_spec.rb
This PR improves error handling when there is a problem in the validator, in two ways:
1. Problems reported as OperationOutcome with an HTTP status other than 200 will raise an `ErrorInValidatorException` which renders in the inferno UI as a purple error, and more detail, when given in the OO, will be in the Messages tab:
(note - this message is introduced in https://github.com/inferno-framework/fhir-validator-wrapper/pull/64 )
(note 2 - a future PR will introduce a better error handler in the validator, which will render errors as OOs. still TBD)
2. When the response from the validator can't be parsed as an OperationOutcome, for example when the validator returns an HTML page that just says "HTTP 500", that will be wrapped in an `ErrorInValidatorException`, and more detail if possible …
=> FI-2035: Improve error handling for validator errors

Gemfile.lock, lib/inferno/config/boot/suites.rb
Original bug: a critical error would result when initializing Inferno with custom test suites that either:
a) had a blank id field (e.g., id = '')
b) had no id field
The console output did not provide meaningful information to the source of the error.
[JIRA ticket link](https://oncprojectracking.healthit.gov/support/browse/FI-2041)
These conditions are now checked for and, if present, will throw a standard error with a specific message during startup.
To reproduce: in `inferno-core` > `dev_suites` > `demo_suite.rb`, edit line 7 with the `id` field to be an empty string or comment out the line entirely.  Then run inferno per the README instructions.
None
=> FI-2041: Custom suites with no ids now throw standard error

Procfile, lib/inferno/apps/cli/main.rb
Bug fix for [FI-2086 webpack not shutting down correctly](https://oncprojectracking.healthit.gov/support/browse/FI-2086)
This PR fixes two bugs related to shutdown of `inferno-core`:
* Issue summary
* When inferno is successfully started via terminal and then exited, the terminal window hangs after the shutdown process has been completed
* Steps to reproduce
1.  Follow `inferno-core` README instructions for preliminary setup
2. Run inferno from the CLI:  `bin/inferno start`
3. Exit with `Ctrl+C` 
4. Shutdown messages will print and all processes will terminate, but the terminal will not fully exit back to the command line prompt until additional keystrokes are entered
* Solution
* Changed Ruby method used to execute shell commands in `main.rb`.  The original `system` method invokes a …
=> FI-2086: fix errors on webpack shutdown

lib/inferno/dsl/fhir_validation.rb, lib/inferno/exceptions.rb, spec/inferno/dsl/fhir_validation_spec.rb
#379 contained a breaking change which was not noticed. We need to revert it so that the functionality can be added in a non-breaking way.
=> Revert "FI-2035: Improve error handling for validator errors (#379)"

lib/inferno/dsl/fhir_validation.rb, lib/inferno/exceptions.rb, spec/inferno/dsl/fhir_validation_spec.rb
This PR is a reissuing of #379 but without changing the method signature of the Validator.validate() function.
This does mean that there are some slight differences between calling `validate` and `resource_is_valid?` - see Notes section below - but the changes in this PR should still be a net positive. `validate` remains the "do it yourself" option and `resource_is_valid?` does everything for you
This PR improves error handling when there is a problem in the validator, in three ways:
1. Problems reported as OperationOutcome with an HTTP status other than 200 will raise an `ErrorInValidatorException` which renders in the inferno UI as a purple error, and more detail, when given in the OO, will be in the Messages tab:
2. When the response from the validator can't be parsed as an …
=> FI-2166: improve validator error handling without changing API

client/src/components/TestSuite/TestSuiteDetails/TestGroupCard.tsx, dev_suites/dev_demo_ig_stu1/groups/demo_group.rb
Added remarkGfm to the TestGroupCard so that tables can be used in descriptions for groups.
Example table added to group 1 in Demonstration Suite
=> FI-2198 Markdown processing added to group level

package-lock.json
We were getting CI test failures on https://github.com/inferno-framework/inferno-core/pull/375 after merging `main` back into that branch on the `npm i` step regarding an invalid checksum on a downloaded npm package.  I investigated to make sure nobody was tampering with npm packages (that would be very bad) somehow.  Go to `main` and run `npm i` and you'll get:
```sh
npm ERR! code EINTEGRITY
npm ERR! sha512-b39TBaTSfV6yBrapU89p5fKekE2m/NwnDocOVruQFS1/veMgdzuPcnOM34M6CwxW8jH/lxEa5rBoDeUwu5HHTw== integrity checksum failed when using sha512: wanted sha512-b39TBaTSfV6yBrapU89p5fKekE2m/NwnDocOVruQFS1/veMgdzuPcnOM34M6CwxW8jH/lxEa5rBoDeUwu5HHTw== but got sha512-QBlUtyVk/5EeHbi7X0fw6liDZc7BBmEaSYn01fMU1OUYbf6GPsbTtd8WmnqbI20SeycoHSeiybkE/q1Q+qlThQ==. (26872 bytes)
```
Turns out we've had an …
=> Fix npm install that fails due to wrong checksum in package-lock.

.env, config/nginx.background.conf, docker-compose.background.yml, lib/inferno/dsl.rb, lib/inferno/dsl/fhir_resource_validation.rb, lib/inferno/entities/test_suite.rb, spec/inferno/dsl/fhir_resource_validation_spec.rb
This PR introduces a new `Inferno::DSL::FHIRResourceValidation` module which is a clone of `Inferno::DSL::FHIRValidation`, modified to support the HL7 validator wrapper. The code is largely the same as the proof of concept in #396 but reworked to be a separate module. The main entry point to use the HL7 wrapper is `fhir_resource_validator` which is the replacement of the `validator` method.
The key differences are as follows:
- The HL7 validator wrapper /validate endpoint request and response use the ValidationRequest and ValidationResponse classes from the org.hl7.fhir.validation library, so we will need to map our input and output appropriately. This is pretty straightforward, see functions wrap_resource_for_hl7_wrapper and operation_outcome_from_hl7_wrapped_response below
- The HL7 …
=> FI-2233: New validation module for HL7 validator wrapper

docs/deployment/database.md, docs/deployment/index.md, lib/inferno/apps/cli/services.rb
Requirements met for fulfilling ticket [FI-2091](https://oncprojectracking.healthit.gov/support/browse/FI-2091)  for this repo.
=> FI-2091 Replaced docker-compose with docker compose

Dockerfile.fhir_resource_validator, docker-compose.background.yml, lib/inferno/config/boot/validator.rb, lib/inferno/dsl/fhir_resource_validation.rb, lib/inferno/jobs.rb, lib/inferno/jobs/invoke_validator_session.rb
The HL7 validator wrapper uses sessions to allow for different combinations of settings to be used on the same server without stomping on each other. Starting up a session can be slow, especially with multiple IGs. This PR introduces a new sidekiq job that runs at startup to spin up a session for each defined validator.
Note 1: We only want to spin up one session per validator, and the "boot" sequence runs on both the web process and any worker processes, so to ensure the job only runs once per validator, the validator boot item breaks out early if running on a worker process.
Note 2: there is an issue in the underlying validation library in the HL7 wrapper where if we try to spin up multiple sessions in a fresh docker container only one will succeed, the rest will fail. See …
=> Backend job to start up sessions on HL7 validator wrapper

dev_suites/dev_demo_ig_stu1/groups/demo_group.rb, lib/inferno/db/migrations/009_add_request_tags.rb, lib/inferno/db/schema.rb, lib/inferno/dsl/fhir_client.rb, lib/inferno/dsl/http_client.rb, lib/inferno/dsl/request_storage.rb, lib/inferno/dsl/resume_test_route.rb, lib/inferno/dsl/runnable.rb, lib/inferno/entities/request.rb, lib/inferno/repositories/requests.rb, lib/inferno/repositories/tags.rb, spec/factories/request.rb, spec/inferno/dsl/fhir_client_spec.rb, spec/inferno/dsl/http_client_spec.rb, spec/inferno/repositories/requests_spec.rb
This branch adds the ability to assign arbitrary tags to requests, and then find requests with particular tags.
This branch includes changes to the db, so be sure to run `bundle exec inferno migrate`.
There are unit tests as well as an example in the demo suite you can mess around with.
=> FI-2330: Request tags

client/src/components/InputsModal/InputRadioGroup.tsx
Fixes a bug where radio button default values weren't being set properly.
Make sure the default radio button value in SMART STU2 for client_auth_type is getting set when mounted.
1. Clone inferno-core.
2. In the `Gemfile`, uncomment this line: `gem 'onc_certification_g10_test_kit'`.
3. In `demo_suite.rb`, uncomment this line: `require 'onc_certification_g10_test_kit'`.
4. Make sure Docker is running and set up Inferno Core locally following the `Running Inferno Core for Development Purposes` instructions in the README. Navigate to [localhost:4567/inferno/](http://localhost:4567/inferno/).
5. In the UI, run all tests for SMART STU2 -- you can use filler values for required fields and cancel out of the wait test. 
6. Open the developer console (right click -> Inspect) and navigate to the …
=> FI-2347: Set radio default input

client/src/components/Header/Header.tsx, client/src/components/SuiteOptionsPage/SuiteOptionsPage.tsx, client/src/components/_common/SelectionPanel/SelectionPanel.tsx
Force header link components to render as if they were `<a>` tags in order to generate a network request.  This allows inferno-deployment to provide the alternate 'test kit' views instead of the suite-centric landing page view.  If not network request is generated when navigating between these components, then there is no way for inferno.healthit.gov to override navigating to them.
=> FI-2383: Force page reroute in header

lib/inferno/dsl/fhir_resource_validation.rb, spec/inferno/dsl/fhir_resource_validation_spec.rb
This PR enables test kits to specify settings for the HL7 validator wrapper via the `cliContext` field of the validation request. The `cliContext` is used to define settings for a validator session such as FHIR version, whether to disable terminology checks, whether code display issues should be a warning or error, etc. 
Example request:
```json
{
"cliContext": {
"sv": "4.0.1",
"ig": [
"hl7.fhir.us.core#4.0.0"
],
"locale": "en"
},
"filesToValidate": [
{
"fileName": "manually_entered_file.json",
"fileContent": "{\"resourceType\": \"Patient\"}",
"fileType": "json"
}
],
"sessionId": "32fc25cf-020e-4492-ace5-03fe904d22e0"
}
```
Essentially [every option from the validator CLI](https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator) is also available here  (though unfortunately the …
=> FI-2236: Support arbitrary fields in HL7 validator cliContext

lib/inferno/apps/web/index.html.erb
Removes margin before React loading to fix slight header jog
=> FI-2392-header-jog

lib/inferno/dsl/oauth_credentials.rb
one-line change to `need_to_refresh?` in `oauth_credentials.rb` to handle an error when `expires_in` is a non-integer type.
=> FI-2329 Add integer conversion to need_to_refresh? method

client/src/components/SuiteOptionsPage/SuiteOptionsPage.tsx
Adds a check for the root of the URL for the new session redirect event; if there is no basePath defined, the root will default to the existing location origin. This will break if the origin and the intended base path are different.
TBD
=> FI-2396-redirect-session

package-lock.json, package.json
Upgrades TypeScript from version 4 to version 5. Override for react-scripts necessary due to open issue https://github.com/facebook/create-react-app/issues/13080.
Should just run as usual + pass all lint/test checks.
=> FI-2182: Upgrade to TypeScript 5

docs/index.md
This just adds a link to the new documentation site that we will be cutting over to next month.  We've made it 'public' by going over it in the tech talk, so may as well add that link now publicly.
Generate and server the docs site locally: https://github.com/inferno-framework/inferno-core#documentation
Ensure that the site looks like below, grammar is ok, and that the links go to the spots that make sense. I used absolute URLs because its just easier because one wouldn't resolve while testing.  This is very temporary, we will be deprecating parts of this inferno_core documentation then.
=> fi-2341 Update docs site to point to preview of new docs site.

lib/inferno/repositories/requests.rb
Postgres doesn't like backticks.
```
ERROR:  syntax error at or near "`" at character 172
STATEMENT:  select final_requests.* from ( select uncounted_requests.request_id request_id from ( select r.id request_id, t.id tag_id from requests r inner join requests_tags rt on r.`index` = rt.requests_id inner join tags t on rt.tags_id = t.id where r.test_session_id = '5Alp5lIjHQ0' and r.result_id in ( SELECT a.id FROM results a WHERE a.test_session_id = r.test_session_id AND a.id IN ( SELECT id FROM results b WHERE (b.test_session_id = a.test_session_id AND b.test_id = a.test_id) OR (b.test_session_id = a.test_session_id AND b.test_group_id = a.test_group_id) OR (b.test_session_id = a.test_session_id AND b.test_suite_id = a.test_suite_id) ORDER BY updated_at DESC LIMIT 1 ) ) and t.name in …
```
=> FI-2426: Fix tagged request query in postgres

lib/inferno/apps/cli/main.rb, lib/inferno/apps/cli/main_spec.rb
Add Inferno version CLI command:
```
$ bundle exec bin/inferno version
Inferno Core v0.4.27
```
I think there should be some option to output test kit version and even HL7 Validator version, but that should be in future tickets/PRs.
2. Run `./bin/inferno version`
=> Fi 2116 inferno version cli

dev_suites/dev_demo_ig_stu1/demo_suite.rb, lib/inferno/dsl/fhir_resource_validation.rb, lib/inferno/dsl/fhir_validation.rb
Set `validator` method to have the default url as the default parameter so that the url does not have to be explicitly declared in the test kits.
=> fi-2237 setting default validator url

lib/inferno/repositories/test_runs.rb
During testing for granular scopes in the US Core test kit, there are several redirects back to Inferno once a large number of tests have already been run. This can result in the session taking over 10 seconds to load in the UI. An initial investigation revealed two slow routes: loading the last test run, and loading all the results.
Before:
The last test run route includes all of the results for that test run, but the UI does not use them. The UI uses the results from the results route, so including the results in the last test run route just results in wasted duplicated effort to load and serialize those results. This branch updates the query used by the last test run route to only return the test run without its results.
After:
Load up g10 and run the single patient api tests on …
=> FI-2434: Remove results from last test run query

lib/inferno/utils/middleware/request_logger.rb
Large payloads in the body of API calls cause the logger to break due to how puma handles very large payloads differently than smaller payloads when parsing.
Ensure that important test kits (e.g. g10) still work properly.  Replicating large input payloads do not break is more challenging, ask team for an example.
=> FI-2463 large request fix

dev_suites/dev_demo_ig_stu1/demo_suite.rb, docs/advanced-test-features/waiting-for-requests.md, lib/inferno/apps/web/controllers/test_runs/destroy.rb, lib/inferno/dsl/resume_test_route.rb, lib/inferno/dsl/runnable.rb, lib/inferno/repositories/results.rb, spec/inferno/dsl/runnable_spec.rb
This allows different URLs to trigger different test results for a waiting test by adding keyword param `result` to `resume_test_route`.
Run the demo suite Wait Group and test the various URLs.
=> FI-2468: Enable different test results in resume_test_route

Gemfile, README.md
We've had several questions internally on the team how to do this, so I'm adding it to the README.  I adjusted the comment slightly for those loading other test kits besides g10.
=> Add instructions for loading external test kits.

lib/inferno/dsl/fhir_resource_validation.rb, spec/inferno/dsl/fhir_resource_validation_spec.rb
Adds the new HL7 validator wrapper cliContext setting `disableDefaultResourceFetcher` to our cliContext defaults. This depends on https://github.com/hapifhir/org.hl7.fhir.core/pull/1526 but can be merged in before that because the hl7 validator wrapper ignores any unrecognized options. (confirmed against the production instance at https://validator.fhir.org/ )
Full details on this setting are available on the ^ linked PR, but it prevents fetching of unknown profiles and extensions, for example when a resource reports a profile in `meta.profile` that is not part of the IG under test. The Inferno validator wrapper does not fetch these profiles so this setting makes the hl7 wrapper match the inferno wrapper in that regard.
Here are the usual notes on using the hl7 validator wrapper:
- enable …
=> FI-2337: add disableDefaultResourceFetcher to fhir_resource_validator.cliContext defaults

docs/index.md
Google still returns the old documentation site which links to the new site at `/index_new.html` that's now a 404. I replaced the link with `https://inferno-framework.github.io` and changed the wording from "before we release it on February 13th."
Intuitively it feels nicer if it links to `/documentation` instead of `/`, but I kept it this way since its probably better for SEO.
I also didn't nit pick the wording or styling around it and maybe we could use a stronger depreciation notice or even a JavaScript redirect but I just wanted to get rid of the 404.  Feel free to close this if something like that is in the works (or I can start a new PR for that if we need it).
Double check my markdown please. I'll use the link inevitably if this gets deployed.
=> Update new website link on old documentation site

client/src/components/TestSuite/TestSession.tsx
When cancelling out of an inputs modal, the run button would be incorrectly marked as "In Progress". This should no longer be happening.
Check this behavior, also click around while tests are running to make sure results/statuses don't get mixed up
=> FI-2562: Fix incorrect progress status on run buttons

lib/inferno/dsl/fhir_client_builder.rb, lib/inferno/dsl/http_client_builder.rb, spec/inferno/dsl/fhir_client_spec.rb, spec/inferno/dsl/http_client_spec.rb
FHIR/HTTP clients were incorrectly using `call` instead of `send` when delegating methods to the runnable in which they are defined.
The unit tests are adequate to demonstrate this failure. Check out `958ef0d28b431d2d01d7cb651d503182b2e8f37b` to see the tests fail.
=> FI-2567: Fix client instance variables

inferno_core.gemspec
It turns out RubyGems wasn't shipping the inferno new templates, so `inferno new my_test_kit` wouldn't work on fresh installs.
You can download the gem from <https://rubygems.org/downloads/inferno_core-0.4.30.gem>, rename it to a .tgz file, extract the contents, and then extract data.tar.gz to verify this.
I ran `npm run build && gem build inferno_core.gemspec` successfully, and then extracted the gem file to make sure lib/inferno/apps/cli/templates was there. However I'm not sure how to fully test this besides waiting for the next release of inferno_core.
=> Fi 2576 inferno new gemspec patch

lib/inferno/repositories/validator_sessions.rb
The `id` column in the table is there just so the db is satisfied that there is a unique `id` pk. It is being replaced with a `SecureRandom.uuid` so that it has a consistent length that does not exceed 36 characters.
=> fix: id should be 36 char long

CHANGELOG.md, Gemfile.lock, lib/inferno/version.rb
* Fi 2576 inferno new gemspec patch by @Shaumik-Ashraf in https://github.com/inferno-framework/inferno-core/pull/465
* fix: id should be 36 char long by @rpassas in https://github.com/inferno-framework/inferno-core/pull/467
=> Release 0431

lib/inferno/apps/web/controllers/test_session_form_post_controller.rb, lib/inferno/apps/web/router.rb, spec/requests/test_sessions_form_post_spec.rb
This branch allows users to do a form POST to `/:suite_id` to create a test session rather than having to rely on the JSON API. I aligned the suite options input handling with what is currently on inferno.healthit.gov, so they're just top-level params rather than any sort of repeating `option` fields.
If you want to manually test this, you'll probably need to create a relevant request in Postman or something similar.
=> FI-2495: Create sessions via form POST

scripts/update_test_kits, update_test_kits.rb
This branch adds a script which goes through each test kit in the `inferno-framework` organization, runs `bundle update`, pushes the changes up to a branch, and opens a PR if a github access token is provided.
Here is a sample PR created by the script: https://github.com/inferno-framework/shc-vaccination-test-kit/pull/12
Once this PR is approved, I will use it to open PRs for all of the test kits.
=> FI-2156: Test kit dependency update script

lib/inferno/dsl/configurable.rb, lib/inferno/test_runner.rb, spec/inferno/dsl/test_creation_spec.rb, spec/inferno/test_runner_spec.rb
If you have a group where one test sets an output that then gets chained into a following tests 'input', if that output is nil when the input is required often times test writers don't think to guard against a nil value. Made fix to inferno core so that before a test is run, it will check each input, and if the input is non-optional and nil, it will skip the test. 
Run `bundle exec rspec` and ensure that all unit tests still pass after this change
=> FI-2349: Input Chaining Fix

lib/inferno/apps/cli/new.rb, lib/inferno/apps/cli/templates/lib/%library_name%.rb.tt
Fixes some wording in the Inferno template resulting from `inferno new ...`. See [this comment](https://github.com/inferno-framework/inferno-core/pull/439#issuecomment-2038229755).
You can checkout this branch and the project folder run `bundle exec bin/inferno new my_kit` to run `inferno new` with the wording fixes. Contextless `inferno new` will only work after the next deploy.
=> New template wording fix

lib/inferno/config/boot/validator.rb
This prevents validator sessions from being created in the test environment. The validator is not expected to be running during unit tests, so it will not be reachable. By default, the validator is going to be using a docker hostname, which causes a DNS error when trying to create a session, preventing unit tests from running in test kits which use the new validator. This happens when Inferno boots (i.e. prior to unit test execution), so this can't be handled by stubbing the requests.
=> FI-2664: Prevent validator sessions from being created in test environment

docs/deployment/database.md
Adds a quick note to the database setup documentation on what to do if you get the replication error mentioned in https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/505
=> Add note about replication error to DB docs

lib/inferno/dsl/fhir_client_builder.rb, spec/inferno/dsl/fhir_client_spec.rb, spec/inferno/dsl/http_client_spec.rb
This branch fixes FHIR operations to avoid double slashes when the base url includes a trailing slash. It was not an issue with the other FHIR interactions or with http client methods.
=> FI-2554: Remove trailing slash

CHANGELOG.md, Gemfile.lock, lib/inferno/version.rb
* Bump follow-redirects from 1.15.5 to 1.15.6 by @dependabot in https://github.com/inferno-framework/inferno-core/pull/479
* Bump express from 4.18.3 to 4.19.2 by @dependabot in https://github.com/inferno-framework/inferno-core/pull/480
* Bump webpack-dev-middleware from 5.3.3 to 5.3.4 by @dependabot in https://github.com/inferno-framework/inferno-core/pull/481
* Bump vite by @dependabot in https://github.com/inferno-framework/inferno-core/pull/482
* Add note about replication error to DB docs by @dehall in https://github.com/inferno-framework/inferno-core/pull/484
* FI-2554: Remove trailing slash by @Jammjammjamm in https://github.com/inferno-framework/inferno-core/pull/485
* FI-2539: Add JSON and YAML file input options by @AlyssaWang in …
=> Release v0.4.35

lib/inferno/config/boot/suites.rb, lib/inferno/dsl/runnable.rb, lib/inferno/entities/test_kit.rb, lib/inferno/repositories.rb, lib/inferno/repositories/test_kits.rb
=> FI-2647 Add TestKit metadata DRAFT

CHANGELOG.md, Gemfile.lock, lib/inferno/version.rb
Aligning changes with published gem - the previously published gem does not include all listed changes.
=> Release 0437

lib/inferno/apps/cli/main.rb, lib/inferno/apps/cli/migration.rb
Automatically run migrations when using `inferno start` or `inferno console`.
Delete `data/inferno_development.db`, then run `bin/inferno start`. The migrations should run and inferno should start.
=> FI-2765: Automatically run migrations

client/src/components/RequestDetailModal/CodeBlock.tsx, client/src/components/RequestDetailModal/styles.tsx
Change color of code block header on hover in the request details modal.
Check that hover effect appears, header should maintain effect while accordion is open. 
Q: Should test list items also have this effect?
=> FI-2753: Add hover effect to request details

client/src/components/RequestDetailModal/CodeBlock.tsx
Adds LOC to the request details modal header.
Check that LOC appears in request details modal.
=> FI-2754: Add lines count to request details

lib/inferno/apps/cli/templates/.env.development, lib/inferno/apps/cli/templates/.env.production, lib/inferno/apps/cli/templates/.env.test, lib/inferno/apps/cli/templates/config/nginx.background.conf.tt, lib/inferno/apps/cli/templates/config/nginx.conf.tt, lib/inferno/apps/cli/templates/docker-compose.background.yml.tt, lib/inferno/apps/cli/templates/docker-compose.yml.tt, lib/inferno/apps/cli/templates/lib/%library_name%.rb.tt, lib/inferno/apps/cli/templates/lib/%library_name%/igs/README.md, lib/inferno/apps/cli/templates/spec/%library_name%/patient_group_spec.rb.tt
Update the "inferno new" template to use the HL7 validator wrapper, as in all of our test kits. One notable difference here is the inferno validator-wrapper and validator UI are not commented out, they are left as-is, so this is mostly just addition other than changing the test suite validator block to `fhir_resource_validator`.
Corresponding changes to the docs are at: https://github.com/inferno-framework/inferno-framework.github.io/pull/32
Re-generate the template with `bundle exec inferno new inferno-template --author "Inferno Template"` and it will be in `./inferno-template`
Sample patient tests should pass, the validator UI should still work as well at http://localhost/validator/ .
YAML to run against reference server:
```yml
- name: url
title: FHIR Server Base Url
type: text
value: …
```
=> FI-2688: Migrate template to HL7 validator wrapper

lib/inferno/dsl/resume_test_route.rb, lib/inferno/dsl/runnable.rb, lib/inferno/dsl/suite_endpoint.rb
When there are multiple consecutive wait tests, there is a race condition which can put Inferno into a state where it fails to resume the test run. This branch reverts `resume_test_route` to no longer be based on suite endpoints which should prevent Inferno from getting into that bad state.
Locally in the PAS test kit, run `bundle update inferno_core`, which should bump core to `0.4.37`. In the client suite, run the `Demonstrate Workflow Support` group, which should end up in a bad state:
This change was released as `0.4.37.dev` so that we could use it in the connectathon. If you set core's version to `0.4.37.dev` in the PAS test kit, or run the same tests on QA, they should no longer hang at this point.
=> FI-2791: Revert resume test route refactor

.env, lib/inferno/apps/cli/console.rb, lib/inferno/config/boot/validator.rb
Creating validator sessions was breaking inferno console when the validator service wasn't running. This branch prevents inferno from initializing validator sessions when using the console.
With no services running:
On main:
- Add the g10 tests following the instructions in the Gemfile
- Run `bundle exec inferno c` and it should fail
On this branch:
- Add the g10 tests following the instructions in the Gemfile
- Run `bundle exec inferno c` and it shouldn't fail
=> FI-2745: Skip loading validator sessions when using inferno console

lib/inferno/dsl/suite_endpoint.rb, lib/inferno/utils/middleware/request_logger.rb
I investigated the incoming requests showing up twice in the UI. I logged the stack trace where each was being persisted:
```
09:31:58 web.1    | **************************START****************************
09:31:58 web.1    | I, [2024-06-17T09:31:58.067544 #64323]  INFO -- : get body
09:31:58 web.1    | /Users/smacvicar/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/inferno_core-0.4.38/lib/inferno/utils/middleware/request_logger.rb:37:in `each'
09:31:58 web.1    | /Users/smacvicar/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/inferno_core-0.4.38/lib/inferno/utils/middleware/request_logger.rb:37:in `call'
09:31:58 web.1    | /Users/smacvicar/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/rack-2.2.9/lib/rack/static.rb:161:in `call'
09:31:58 web.1    | …
```
=> FI-2836: Fix double requests from suite endpoints

lib/inferno/apps/cli/templates/lib/%library_name%.rb.tt
Fix typo
2. cd tmp
3. ../bin/inferno new test_template
4. Make sure the new test suite works. Typo fix is in lib/test_template.rb line 24.
I'll run `./scripts/publish_template` after this is merged to update inferno template repository.
=> Fix typo 'requests' in inferno template

lib/inferno/apps/cli/main.rb
IT WORKED! This is a rogue PR but please let this be a feature, maybe after the upcoming push to production. Putting up as draft (see TODOs below), but I'm not opposed to just merging it if people approve.
1. Check out this branch
2. `bundle exec bin/inferno services`
3. `bundle exec bin/inferno start`
1. ~~It still outputs "You must install foreman with 'gem install foreman' prior to running Inferno" because it can't detect foreman in the bundler env, but then will still run anyways in non-bundler env. We can fix this with another `if` but I'll try to do it in a cleaner way.~~ Resolved
2. While we're doing this, do we want to handle the case of if they have foreman installed within the bundler env? IMHO that would be too opinionated.
3. Rspec it
=> Make `bundle exec inferno start` work

client/src/components/TestSuite/TestSuiteDetails/TestListItem/InputOutputList.tsx
Original issue: https://oncprojectracking.healthit.gov/support/browse/FI-2724
Problem: contents in Inputs and Outputs are converted to markdown. Though it's useful for styles, can cause problems when strings like URLs are broken by that.
Fix: removed React Markdown in the HTML.
1. Run Inferno core
2. Try markdown contents in entry (e.g. bearer_token: `~~SAMPLE_TOKEN~~`)
3. In the results, contents SHOULD NOT be converted into markdown.
`react-markdown` is being used as below. Further investigation needs to figure out whether markdown is being used unnecessarily.
=> Remove ReactMarkdown in Inputs/Outputs

README.md
I was reviewing the Inferno Core README and noticed several broken links (since we move docs from /inferno-core subdir of the docs site).  While fixing that, I cleaned up some of the content a bit.  I also noticed that we don't document how to create a custom banner in Test Kits in the docs site, which should be documented there and not in the Inferno Core README (except for those interested in contributing to Inferno Core directly).
Just read over the changes and look for grammar issues.
This falls under 'documentation' so I've tagged @mrnosal for a review.
=> Update README content; fix broken links and improve generally.

dev_suites/dev_auth_info/auth_info_suite.rb, lib/inferno/dsl/auth_info.rb, lib/inferno/dsl/fhir_client_builder.rb, lib/inferno/ext/fhir_client.rb, spec/inferno/dsl/auth_info_spec.rb
This branch updates the fhir client to support auth info.
- it adds the `auth_info` attribute to a fhir client
- it uses credentials from auth info when making requests
Updated tests in the access mode group of the auth info suite to verify that `auth_info` is properly declare when defining `fhir_client`. The tests will verify that the `fhir_client.auth_info` attributes are what is expected.
=> FI-2863: Added support for auth_info to fhir_client

lib/inferno/apps/web/router.rb, lib/inferno/config/application.rb, lib/inferno/dsl/auth_info.rb, spec/fixtures/auth_info_constants.rb, spec/inferno/dsl/auth_info_spec.rb, spec/requests/jwks_spec.rb
This branch hosts the JWKS used for signing client assertions in core, and populate the `jku` field in the client assertion with the JWKS url.
- Run unit tests and ensure passing
- Start Inferno and ensure http://localhost:4567/inferno/jwks.json resolves, returning the JWKS in json.
=> FI-2910: Host JWKS for Client Assertion

client/src/components/RequestDetailModal/RequestDetailModal.tsx
Fixes a typo that prevented the request body from appearing properly in the RequestDetailsModal.
For a test with a request body, check the Details modal to ensure that it appears.
=> FI-2990: Fix typo in Request Details Modal

.rubocop.yml, lib/inferno/dsl/fhir_resource_validation.rb, lib/inferno/dsl/fhir_validation.rb, lib/inferno/jobs/invoke_validator_session.rb, spec/inferno/dsl/fhir_resource_validation_spec.rb, spec/inferno/dsl/fhir_validation_spec.rb
**Ticket Description**: We saw an issue where a validator response contained a null character and it crashed the test runner, so it kept spinning forever. Since we don't control the validator and especially the tx server, make sure an unexpected response doesn't crash anything.
I was able to reproduce the issue by mocking the validator service with various unexpected response formats, including non-printable/control characters, which led to crashes when the test runner attempted to persist the response. By using Mockoon to simulate these edge cases, I confirmed that the issue was specifically related to non-printable characters in the response body, which caused SQLite exceptions during persistence.
**Changes Made**:
- **Sanitized the response body**: The response body is now sanitized to …
=> FI-2728: Prevent Test Runner from Crashing When Validator Response Contains Bad Characters

README.md
I do not see a reason to have just this type of documentation in the inferno core readme.  The appropriate place is the documentation site.
We've added that in https://github.com/inferno-framework/inferno-framework.github.io/pull/52
FYI @mrnosal
=> FI-2887 Remove banner info from readme because that belongs in the docs site.

spec/fixtures/auth_info_constants.rb
Reading the `jwks.json` template in spec using relative path raised a  no file error when using the gem in test kit test environment. This PR updates the jwks path to the correct absolute path.
Test by pointing inferno_core gem to this branch and ensure no error when executing rspec.
=> FI-3112: Fixed JWKS Template Path Used in Unit Tests

lib/inferno/dsl/fhir_resource_validation.rb
See that this passes CI and run a dev suite
=> patch undefined method for nil on validator 500 response

lib/inferno/dsl/fhir_resource_validation.rb
Updates [docs](https://inferno-framework.github.io/inferno-core/docs/Inferno/DSL/FHIRResourceValidation/Validator.html) to remove redundant example that is also bad ruby.  I believe we had already gotten the bad ruby example fixed on the framework site but didn't get it fixed here.
Also, figured we might as well include the exampleURL flag as an example because that was the one I actually wanted to use when i was looking at this documentation.
I suppose you could regenerate the docs as explained in the readme.  Also, I haven't tried out that example url flag technically, but [grabbed it from the  wrapper UI config](https://github.com/hapifhir/org.hl7.fhir.validator-wrapper/blob/0093f0b02b9b88c86cf4e1da75d4aed410acf8d5/src/commonMain/resources/static-content/openapi.yml#L218C13-L218C29) so …
=> FI-3188: Update documentation on cli_context options.

lib/inferno/apps/cli/templates/.gitignore
Adding gitignore for .gem files so they do not accidentally get tracked when the template is used for new test kits
=> cli git ignore .gem

lib/inferno/apps/cli/execute.rb
Found a bug on inferno execute where it was requiring inputs that should not be required. The diff will explain a lot.
2. Make a new branch: `git checkout -b bug-execute-input-validation-test`
3. Merge PR #540: `git merge origin/fi-3182-clean-diff`
4. Run this, which fails on main and fi-3182-clean-diff, but should succeed now:
```
bundle exec inferno execute --suite infra_test -g 1 -t 4.01 --inputs suite_input:a outer_group_input:b inner_group_input:c test_input:d
```
Have to do it this way because #540 includes another bug fix, but I feel that this bug fix should get merged separately and sooner.
=> FI-3275 debug: inferno execute input validation

README.md
Add instruction on using `./bin/docs` to build Ruby Docs
=> FI-3193 Add instruction to build Ruby Docs

docs/Gemfile.lock, lib/inferno/dsl/auth_info.rb
The code documentation for AuthInfo was not properly formatted. Updated the doc to ensure proper rendering
Generate the doc locally with `./bin/docs` and ensure proper rendering.
=> FI-3276: Fix AuthInfo Code Documentation

client/src/components/InputsModal/AuthTypeSelector.tsx, client/src/components/InputsModal/__tests__/Inputs.test.tsx
Updates Auth Type input title to remove parent input name.
Check that Auth Type only has the title `Auth Type`.
=> FI-3286: Rename Auth Type dropdown input

lib/inferno/dsl/runnable.rb, lib/inferno/exceptions.rb, spec/inferno/dsl/runnable_spec.rb
Some runnable ids were becoming longer than the length limit on the columns for runnable ids in the database. SQLite doesn't actually enforce those limits, so this issue wouldn't be noticed until trying to run on QA/prod. This branch checks runnable ids on creation so that they will be noticed immediately.
You can do something like change the id of the demo suite to `'a' * 256`, and Inferno will fail to start.
=> FI-3241: Verify runnable id length

client/src/components/InputsModal/InputCheckboxGroup.tsx, client/src/components/InputsModal/InputHelpers.ts, client/src/components/InputsModal/InputsModal.tsx
This bug was caused by some checkbox inputs getting improperly processed as JSON strings when they were actually arrays of strings. Adding a case to handle this particular typing prevents the error. This PR also refactors some of the InputModal logic to simplify the component logic and provide more consistent reactive handling of required inputs.
To reproduce: try to run Demo Group 1 in the Demonstration Suite; the Submit button should be disabled even though all required inputs have values.
After these changes, this should no longer occur -- all inputs should behave according to required input status. Also test JSON and YAML inputs to ensure those features still work as expected.
=> FI-3318: Fix erroneous submit disabling for checkbox inputs

lib/inferno/apps/cli/execute.rb, lib/inferno/apps/cli/main.rb
I realized execute was not respecting result summarizer rollup behavior at all, and with this PR it will at least respect the old behavior. Customized rollup behavior is still not supported (because the children of custom rollup groups make their way into the results array). I'll patch that bug in a future PR and ticket. 
This PR along with inferno-framework/tls-test-kit#20 and onc-health/onc-certification-g10-test-kit#577 is blocking inferno-framework/inferno-reference-server#182, which is succesfully running g10 in CI.
Just see the working CI run: <https://github.com/inferno-framework/inferno-reference-server/actions/runs/11524446739/job/32084615655?pr=182>
=> FI-3367 Patch execute rollup

.env, lib/inferno/exceptions.rb, lib/inferno/repositories/in_memory_repository.rb, spec/inferno/entities/test_suite_spec.rb, spec/inferno/repositories/presets_spec.rb, spec/inferno/repositories/test_suites_spec.rb, spec/inferno/web/serializers/test_group_spec.rb
This PR addresses a performance issue in the JSON API caused by collisions of entity or runnable IDs. Duplicate IDs lead Inferno to reindex tests every time a test is fetched from the repository, significantly impacting performance. To prevent this, the PR introduces a check that detects duplicate IDs before entities are inserted into the repository. If duplicates are found, Inferno will fail to start, prompting the user to resolve the ID collisions.
- Tested with the G10, which contains duplicate test IDs in the US Core Test Kit.
- Confirmed that Inferno fails to start due to the detected duplicates
=> FI-3358: Check for Duplicate Ids in In-Memory Repositories

lib/inferno/entities/request.rb
This PR ensures that the verb attribute of the Request entity is consistently converted to lowercase during instantiation from all sources (Hamani, HTTP responses, or FHIR client).
=> FI-3223: Ensure Request Entity Verb Is Always Downcased

CHANGELOG.md, Gemfile.lock, lib/inferno/version.rb
* FI-3358: Check for Duplicate Ids in In-Memory Repositories by @vanessuniq in https://github.com/inferno-framework/inferno-core/pull/551
* FI-3223: Ensure Request Entity Verb Is Always Downcased by @vanessuniq in https://github.com/inferno-framework/inferno-core/pull/554
=> Release v0.5.0

client/src/components/InputsModal/AuthTypeSelector.tsx, client/src/components/InputsModal/InputAccess.tsx, client/src/components/InputsModal/InputAuth.tsx
Options for the auth selector were previously hardcoded. This change will pull options from the provided input instead.
Pull this branch into authinfo-flex to test
=> FI-3469: Use provided auth input options

inferno_core.gemspec, lib/inferno/apps/cli/templates/Gemfile.tt, lib/inferno/apps/cli/templates/spec/%library_name%/patient_group_spec.rb.tt, lib/inferno/apps/cli/templates/spec/spec_helper.rb.tt, lib/inferno/dsl/resume_test_route.rb, lib/inferno/spec_support.rb, spec/inferno/entities/test_group_spec.rb, spec/inferno/entities/test_suite_spec.rb, spec/runnable_context.rb, spec/runnable_helper.rb, spec/spec_helper.rb
This branch factors out common unit testing behaviors. For a demonstration of a test kit using this functionality, see https://github.com/inferno-framework/subscriptions-test-kit/pull/13
The template has also been updated to use these shared behaviors. If you generate a new test kit, comment out the inferno_core requirement in the gemspec, and point at this inferno_core branch in the Gemfile, the unit tests should pass in the created test kit.
=> FI-3475: Unit testing improvements

lib/inferno/entities/test_session.rb
I suspect rubocop broke it here: https://inferno-framework.github.io/inferno-core/docs/Inferno/Entities/TestSession.html#test_suite-instance_method
=> Fix Inferno::Entities::TestSession docs

CHANGELOG.md, Gemfile.lock, lib/inferno/version.rb
* FI-3097: Maintain checkbox label colors on error by @AlyssaWang in https://github.com/inferno-framework/inferno-core/pull/537
* Fi 2962 execute outputters by @Shaumik-Ashraf in https://github.com/inferno-framework/inferno-core/pull/541
* FI-3469: Use provided auth input options by @AlyssaWang in https://github.com/inferno-framework/inferno-core/pull/560
* FI-3475: Unit testing improvements by @Jammjammjamm in https://github.com/inferno-framework/inferno-core/pull/559
* FI-3023: Add default env vars and documentation to validator dockerfile by @dehall in https://github.com/inferno-framework/inferno-core/pull/562
* Fix Inferno::Entities::TestSession docs by @Shaumik-Ashraf in https://github.com/inferno-framework/inferno-core/pull/563
**Full Changelog**: …
=> Release v0.5.1

client/src/components/InputsModal/InputsModal.tsx, client/src/components/SuiteOptionsPage/SuiteOptionsPage.tsx, client/src/components/TestSuite/ConfigMessagesDetails/ConfigMessagesDetailsPanel.tsx, client/src/components/TestSuite/TestSuiteDetails/TestGroupCard.tsx, client/src/components/TestSuite/TestSuiteDetails/TestGroupListItem/NestedDescriptionPanel.tsx, client/src/components/TestSuite/TestSuiteDetails/TestListItem/MessageList.tsx, client/src/components/TestSuite/TestSuiteDetails/TestListItem/TestListItem.tsx, client/src/components/TestSuite/TestSuiteDetails/TestListItem/TestRunDetail.tsx, client/src/components/_common/ActionModal.tsx, client/src/index.css, dev_suites/dev_demo_ig_stu1/groups/demo_group.rb
Adds a bar on the left of blockquotes. 
Open to feedback about appearance, e.g. bar should be thicker!
Visual test with Demo Suite -- blockquotes should show up with a bar on the left.
=> FI-3019: Add custom blockquote styles

config/presets/dev_validator_preset.json, lib/inferno/apps/cli/execute.rb, lib/inferno/apps/cli/main.rb, lib/inferno/config/boot/executor.rb, spec/fixtures/dev_validator_preset_2.json, spec/inferno/cli/execute_spec.rb
Adds two CLI options for `inferno execute`:
- `--preset-id` that will load a preset by id from directories listed in [lib/inferno/config/boot/presets.rb](https://github.com/inferno-framework/inferno-core/tree/main/lib/inferno/config/boot/presets.rb). This helps test kit authors.
- `--preset-file` that will load a preset from a given file path. This helps test kit CI users.
- Both `--preset-id` and `--preset-file` cannot be used together. However `--inputs` can be used with either of those options, and inputs will merge with and override presets.
2. Start inferno services
3. Confirm this command works:
```
bundle exec inferno execute --suite dev_validator --preset-id dev_validator_preset
```
4. Prepare another preset file, i.e: `cp …
=> FI-2961 execute preset support

lib/inferno/result_summarizer.rb, spec/inferno/result_summarizer_spec.rb
This branch fixes the result summarizer to properly handle optional tests with wait results.
Load up a test kit with an optional wait test, and it should behave properly on this branch.
=> FI-3550: Handle optional waiting results

validator/Dockerfile
Upgrades the inferno-resource-validator Dockerfile to match the latest upstream changes in https://github.com/hapifhir/org.hl7.fhir.validator-wrapper v1.0.60
Specifically this adds a couple lines that enable the fhir package cache to work as a docker volume, from https://github.com/hapifhir/org.hl7.fhir.validator-wrapper/commit/b006e3c669584f9e06c530ea1aba3070810d2828
To build just this image and load it locally:
```
docker buildx build --platform linux/arm64 --build-arg "PROJECT_VERSION=1.0.60" --tag "infernocommunity/inferno-resource-validator:1.0.60" --tag infernocommunity/inferno-resource-validator:latest --load .
```
Then to map a volume, uncomment this line in the docker-compose here or in your favorite test kit: https://github.com/inferno-framework/inferno-core/blob/637a014e9744d966 …
=> FI-3565: Upgrade validator dockerfile to match upstream

lib/inferno/apps/cli/new.rb, lib/inferno/apps/cli/templates/%library_name%.gemspec.tt, spec/inferno/cli/new_spec.rb
This branch updates the gemspec in the template to include files based on what is committed to git. This will help avoid the issue where a test kit gem is published but new files are not included because they do not meet the criteria for inclusion in the gemspec.
- `bundle exec bin/inferno new my_test_kit`
- `cd my-test-kit`
- `mkdir config/presets`
- `touch config/presets/my_preset.json`
- `git add config`
- `git commit -m "add preset"`
- `gem build my_test_kit.gemspec`
- `mkdir gem`
- `mv my_test_kit-0.0.0.gem gem`
- `cd gem`
- `tar -xvf my_test_kit-0.0.0.gem`
- `tar -xvzf data.tar.gz`
You should see all of the expected files (everything in lib and the preset).
=> FI-3588: Use git for files in test kit gemspecs

client/src/components/InputsModal/AuthSettings.ts, client/src/components/InputsModal/AuthTypeSelector.tsx, client/src/components/InputsModal/InputAccess.tsx, client/src/components/InputsModal/InputAuth.tsx
Bug fix for the following: 
**Current behavior:** Auth inputs check first component provided for default selection settings. If another component is provided, inputs break.
**Expected behavior:** Inputs should find first component with type auth
_See branch fi-3093-debug_
Pull this branch into fi-3093-debug -- should be able to open inputs without errors. Check auth inputs, access inputs, and type selector; all should work.
Cases to check: 
1. `components` is empty and/or undefined -- AuthInfo Suite
2. `components` has only `auth_type` -- AuthInfo Suite
3. `components` has only something else -- SMART STU1
4. `components` has something else and `auth_type` -- add the following to `InputAuth.tsx` on line 22:
`input.options?.components?.push({
name: 'auth_type',
default: 'symmetric',
});` …
=> FI-3643: Check input components for auth

inferno_core.gemspec, lib/inferno/spec_support.rb, spec/shared/test_kit_examples.rb
This branch creates a set of shared examples which test kits can import to ensure that they meet the requirements to be deployed on inferno.healthit.gov.
Check out the `fi-3338-test` branch in the US Core Test Kit, `bundle`, and `bundle exec rake` to run these tests.
=> FI-3338: Create common test kit specs

Gemfile.lock, inferno_core.gemspec, lib/inferno/apps/cli/templates/Dockerfile.tt
This PR fixes onc-healthit/onc-certification-g10-test-kit#610 and the broken `inferno new` command. The bugs are due to [activesupport and concurrent-ruby gems](https://github.com/rails/rails/issues/54272). Activesupport PR rails/rails#54264 should also fix it but has not been released yet.
2. Generate a new test kit:
```
bundle exec inferno new fix-test
```
3. Add this line to `fix-test/Gemfile`:
```
gem 'inferno_core', git: 'https://github.com/inferno-framework/inferno-core', branch: 'pin-concurrent-ruby-1.3.4'
```
4. Make sure the new test kit works via Docker:
```
cd fix-test
./setup.sh
./run.sh
```
5. Clean up
```
cd ..
rm -rf fix-test
```
=> Pin concurrent-ruby to 1.3.4

Gemfile.lock, lib/inferno/dsl/fhir_resource_validation.rb, lib/inferno/dsl/fhir_validation.rb, spec/inferno/dsl/fhir_resource_validation_spec.rb, spec/inferno/dsl/fhir_validation_spec.rb
This branch updates the existing method `resource_is_valid?` to conditionally log in messages to runnable to accomodate scenario where the user may not want to log validation messages. The method was updated by adding an additional parameter `add_messages_to_runnable` with a default value of true, that can be toggle off or on depending on the use case.
=> FI-3178: Validate Resource Without Validation Messages

lib/inferno/apps/cli/templates/.github/workflows/publish-docs-wiki.yml, lib/inferno/apps/cli/templates/README.md.tt, lib/inferno/apps/cli/templates/docs/Overview.md, lib/inferno/apps/cli/templates/docs/README.md.tt, lib/inferno/apps/cli/templates/docs/_Footer.md, lib/inferno/apps/cli/templates/docs/_Sidebar.md
This adds basic docs to the template.  I put a preview of what it should look like when you generate it over [here](/arscan/inferno-template).
Note that the workflow action will not work until you create a Wiki for the repo in GitHub (go to `Wiki` and just click a button).  I don't love having a failing thing by default, but it will only get run when users change `./docs`, and I expect once they change it they will see the instructions to create the wiki, so I do not expect any more than 1 failing run of this thing (at most; maybe even 0).
Once merged, we need to update /inferno-framework/inferno-template; that's quite far behind which is why I didn't bother showing this off on a branch over there.
=> fi-3227 Add docs to template.

spec/runnable_context.rb
This branch updates the runnable context to support using the runnable spec helpers when describing a non-runnable (e.g., a module that is included in runnables).
=> FI-3678: Update runnable context to support use when describing non-runnables

spec/runnable_context.rb
This branch adds the ability to pass `scratch` to the `run` method in the runnable context.
[This g10 branch] was updated to use this functionality, and its unit tests should pass if you point `inferno_core` it at this branch in its Gemfile, but will fail if you point it at the main branch of `inferno_core`. In [that g10 branch's last commit](https://github.com/onc-healthit/onc-certification-g10-test-kit/pull/619/commits/6a02ebcc1e0392ec920e0b2d1f8193943fd37d25#diff-840673ba113751ed304c37171e616b9d5f45487fe651890e28a3747c6fe05af4L40), you can see that a `run` method which included `scratch` was removed.
=> FI-3732: Add scratch to runnable context

dev_suites/dev_options_suite/options_suite.rb, docs/swagger.yml, lib/inferno/apps/web/serializers/suite_option.rb, lib/inferno/dsl/suite_option.rb, spec/inferno/web/serializers/suite_option_spec.rb
This branch adds the ability to assign a default value to suite options.
The new unit test verifies that the default value is serialized.
If you make a request to `http://localhost:4567/inferno/api/test_suites/options`, you will see that a default value is transmitted via the JSON API.
=> FI-3756: Add suite option default

lib/inferno/apps/web/controllers/controller.rb, lib/inferno/apps/web/router.rb
This branch fixes some JSON API responses which didn't have a JSON content-type. It also fixes the content-type in a few other routes.
Open the network tab in your browser inspector. On main, you will see that the responses to some api requests have a content-type of plain or octet-stream. On this branch, the responses should all have correct content types.
=> FI-3487: Fix response content types

lib/inferno/dsl/runnable.rb, spec/inferno/dsl/runnable_spec.rb
This branch adds a `remove` method which can be used to remove a child test/group.
The unit test covers it.
=> FI-3714: Add method to remove runnables

client/src/components/TestSuite/TestSuiteDetails/TestGroupListItem/TestGroupListItem.tsx, client/src/components/TestSuite/TestSuiteDetails/TestListItem/TestListItem.tsx
Refactors cursor behavior to allow tooltips on hover. Also removes the ability for expansion to be modified via tab-through keyboard events. Changes cursor to default instead of pointer in this use case.
Mouse over icons in report view -- tooltips should appear.
Click expansion and tab-through keyboard expansion of accordion items should be disabled.
=> FI-3731: Modify cursor behavior to allow tooltips in report

.rubocop.yml, lib/inferno/dsl/results.rb, spec/inferno/dsl/results_spec.rb
This branch updates `skip` and `omit` to optionally take a block, and skip/omit if an assertion within that block fails.
Unit tests cover these cases.
=> FI-3778: Allow skip and omit to take blocks

client/src/components/InputsModal/InputHelpers.ts, client/src/components/InputsModal/InputsModal.tsx
Empty fields in JSON values were being set to empty strings automatically, causing type errors. Now, before input submission, JSON values get parsed and cleaned of empty strings such that only fields with filled in values are sent over.
This can be a bit tricky to test -- if there's no test suite where empty string validation is important, then:
1. Add `console.log(JSON.parse(inputsWithValues[0].value));` to line 170 in `InputsModal.tsx`
2. Go to AuthInfo suite -> Auth mode -> Run Backend Services
3. Delete optional values (Key ID and JWKS) and submit
4. The console should print the submission values -- note that optional fields are not shown
=> FI-3713: Delete empty fields from JSON inputs

dev_suites/dev_auth_info/auth_info_suite.rb, lib/inferno/dsl/runnable.rb, lib/inferno/exceptions.rb, lib/inferno/repositories/in_memory_repository.rb, spec/inferno/dsl/runnable_spec.rb
This branch adds a `replace` method to replace a child test/group.
Passing unit tests
=> FI-3715: Add Method to Replace Runnables

.github/workflows/ui.yml
This branch adds an action to automatically push an update which includes the built UI to the `ci-main-ui` branch whenever `main` is updated. This will allow test kits/platforms to easily preview inferno core updates which have been merged but not yet released.
In a test kit, add the following to the `Gemfile`:
```ruby
gem 'inferno_core',
git: 'https://github.com/inferno-framework/inferno-core.git',
branch: 'main'
```
Run `bundle`, then start inferno. When you navigate to inferno in the browser, the UI won't load because the UI isn't included in the `main` branch.
Change the code in the Gemfile to point at `ci-main-ui` rather than `main`, run `bundle` and restart inferno. Now when you navigate to inferno the UI should load as normal.
=> FI-3722: Add branch for built UI

.env.test, dev_suites/dev_demo_ig_stu1/demo_suite.rb, dev_suites/dev_options_suite/options_suite.rb, lib/inferno/dsl/fhir_resource_validation.rb, lib/inferno/dsl/fhir_validation.rb, spec/inferno/dsl/assertions_spec.rb, spec/inferno/dsl/fhir_resource_validation_spec.rb, spec/inferno/dsl/fhir_validation_spec.rb, spec/inferno/test_runner_spec.rb, spec/shared/test_kit_examples.rb
This branch adds a deprecation warning to the old validator and switches dev suites and unit tests to rely on the new validator.
If you check out `7ac6aedc1a8dc8a930445acc91a9ab1d0ec51aaa` and start Inferno, you will see the deprecation warnings for the validators in the dev suites.
=> FI-3771: Deprecate legacy validator

lib/inferno/config/boot/ig_files.rb
There was a type mismatch where `+=` was being used to add a hash to an array instead of `<<`
=> FI-3821: Fix IG file loading

lib/inferno/apps/cli/evaluate.rb, lib/inferno/dsl/fhir_evaluation/profile_conformance_helper.rb, spec/inferno/dsl/fhir_evaluation/profile_conformance_helper_spec.rb
Integrates the validator service into the evaluator CLI tool. As of right now the only way this is used is as a heuristic for resource selection for profile conformance, for instance in a rule "all profiles must have examples", we can say that if a resource conforms to a profile then it is an example of that profile.
The framework for this is already in place, so the key change here is just to fill in a few blanks. The only quirk is that if we want to evaluate against an IG by file, and that file isn't already in the new data/igs directory, we need to copy it there so that it's accessible to the validator container. Referencing an IG by identifier, eg `hl7.fhir.us.core#3.1.1`, works as-is in the validator so no need to do anything special in that case.
By default, the new feature is …
=> FI-3626: Integrate validator service into evaluator CLI

lib/inferno/dsl/auth_info.rb, spec/inferno/dsl/auth_info_spec.rb
This branch rescues and logs errors when an AuthInfo object has an invalid issue time.
Add the following to the `Gemfile` and run `bundle`:
```ruby
gem 'davinci_us_drug_formulary_test_kit',
git: 'https://github.com/inferno-framework/davinci-us-drug-formulary-test-kit.git',
branch: 'fi-3746-use-authinfo'
```
Add `require 'davinci_us_drug_formulary_test_kit'` to the demo suite, start inferno, and the formulary tests should work with the preset. If you do the same on `main`, you will be unable to run the tests.
=> FI-3882: Handle AuthInfo date parsing errors

lib/inferno/apps/cli/evaluate.rb
This PR fixes an issue that causes the `inferno migrate` task to fail with an error. The `evaluate` task requires the repositories so that it can read/persist validator session IDs, but this broke the `migrate` task when the tables don't already exist. The fix (for now at least) is to just move the require into a method call so that it's not invoked for all the other unrelated rake tasks. 
To make sure the evaluator still works:
- Set the evaluator to use the validator by changing settings in `lib/inferno/dsl/fhir_evaluation/default.yml`:
- Start up the background services `bundle exec inferno services start`
- Run an evaluation, eg `bundle exec inferno evaluate ./spec/fixtures/uscore311.tgz` . 
- This may take a while so if you don't want to wait for it to finish, just confirm no ruby …
=> FI-3908: Change how evaluator CLI requires repositories, fixing migrate task

validator/Dockerfile, validator/README.md
Adds a new environment variable to our `infernocommunity/inferno-resource-validator` dockerfile to disable loading presets at service startup. Unfortunately there's no explicit value or setting to disable presets, we have to just point it to a non-existent path. Hence I gave it a name that hopefully makes it obvious the error message it prints is intentional.
The logs at startup now look like this:
```
2025-04-03 08:31:33 Starting instance in 0.0.0.0:3500
2025-04-03 08:31:34 Attempting to load presets from ignore-this-do-not-load-presets
2025-04-03 08:31:34 Error occurred loading presets. No presets will be loaded
2025-04-03 08:31:34 java.io.FileNotFoundException: ignore-this-do-not-load-presets (No such file or directory)
2025-04-03 08:31:34     at …
```
=> FI-3867: Add new env var to validator dockerfile to disable presets

lib/inferno/config/boot/requirements.rb
Quick followup bugfix to FI-3600: when running a test kit standalone, the new requirements boot process is pulling in the local requirement files twice (once as `lib/*test_kit/requirements/*.csv`, once as `File.join(gem.full_gem_path, 'lib', '*test_kit', 'requirements', '*.csv')`). 
This causes errors like the following and prevents the UI from starting.
```
08:52:01 web.1    | ! Unable to load application: Inferno::Exceptions::DuplicateEntityIdException: ID 'hl7.fhir.us.carin-bb_2.0.0@1' already exists. Ensure the uniqueness of the IDs.
08:52:01 web.1    | /Users/dehall/.rvm/gems/ruby-3.3.6/bundler/gems/inferno-core-f6b3046637fc/lib/inferno/repositories/in_memory_repository.rb:12:in `insert': ID 'hl7.fhir.us.carin-bb_2.0.0@1' already exists. Ensure the uniqueness of the IDs. …
```
=> Fix for requirements loading twice

dev_suites/dev_options_suite/options_suite.rb, dev_suites/dev_requirements/requirements/sample_requirements.csv, dev_suites/dev_requirements/requirements_suite.rb, lib/inferno/apps/web/controllers/test_suites/requirements/index.rb, lib/inferno/apps/web/serializers/requirement_set.rb, lib/inferno/apps/web/serializers/test_suite.rb, lib/inferno/dsl/requirement_set.rb, lib/inferno/dsl/suite_requirements.rb, lib/inferno/entities/requirement.rb, lib/inferno/entities/test_suite.rb, lib/inferno/repositories/requirements.rb, spec/inferno/dsl/requirement_set_spec.rb, spec/inferno/entities/requirement_spec.rb, spec/inferno/repositories/requirements_spec.rb, spec/inferno/web/serializers/test_suite_spec.rb, spec/requests/test_suites_spec.rb
This branch adds support for declaring which sets of requirements a suite tests. This will form the foundation for upcoming requirements UI work.
Requirement sets should be visible in the console or in API responses for the dev suites which have been updated to use them.
=> FI-3939: Add support for requirement sets

lib/inferno/dsl/fhir_evaluation/default.yml, lib/inferno/dsl/fhir_evaluation/rules/all_search_parameters_have_examples.rb, spec/inferno/dsl/fhir_evaluation/rules/all_search_parameters_have_examples_spec.rb
Running the evaluator CLI when the fhirpath service isn't running produces some unexpected error messages in the results. This PR addresses this issue by 
- The error message should be more clear that the evaluation couldn't be performed because the service isn't running.
- The AllSearchParametersHaveExamples rule shouldn't run if the fhirpath service isn't available.
1. Added a method `fhirpath_is_available?` to check if the fhirpath service is available. If not the rule stops.
2. If the service is failed by other reasons, it returns details to be handled by the rule.
All US Core versions have some failed evaluation due to wrong number of arguments.
Examples:
```
WARNING: SearchParameter http://hl7.org/fhir/us/core/SearchParameter/us-core-condition-onset-date failed to evaluate due to an …
```
=> Fi 3950 Handle Error message in evaluator CLI when fhirpath service not running is unclear

lib/inferno/entities/requirement.rb, lib/inferno/repositories/requirements.rb, spec/inferno/entities/requirement_spec.rb
- Fixes a bug in `expand_requirement_ids` where non-numeric range inputs (e.g., cds-hooks_2.0) would raise an exception.
1. Checkout the `fi-4047-demo` branch.
2. Run `bundle install`, then start Inferno. It should should exit with duplicate requirement ID error
3. Now, point `inferno_core` to the `main` branch, run `bundle install`, and restart Inferno. It will hang and fail to start.
=> FI-4047: Improve Requirement ID Expansion

.rubocop.yml, dev_suites/dev_requirements/requirements/sample_requirements.csv, lib/inferno/apps/cli/requirements_exporter.rb, lib/inferno/entities/requirement.rb, lib/inferno/repositories/requirements.rb, spec/fixtures/simple_requirements.csv, spec/inferno/cli/requirements_exporter_spec.rb, spec/inferno/repositories/requirements_spec.rb
This branch merges the requirements and not-tested CSVs into a single CSV file. For now, untested requirements are not included in requirement sets which include all requirements for a particular actor. They are include if they are explicitly included by id, or are referenced as a sub-requirement. A future ticket will include them all the time once the UI considerations have been taken into account.
=> FI-4106: Handle not tested requirements

dev_suites/dev_infrastructure_test/infrastructure_test_suite.rb, dev_suites/dev_infrastructure_test/serializer_group.rb, dev_suites/dev_infrastructure_test/serializer_test.rb, docs/swagger.yml, lib/inferno/apps/web/serializers/test.rb, lib/inferno/apps/web/serializers/test_group.rb, lib/inferno/apps/web/serializers/test_suite.rb, spec/inferno/web/serializers/test_group_spec.rb, spec/inferno/web/serializers/test_spec.rb, spec/inferno/web/serializers/test_suite_spec.rb
This branch adds the ids from `verifies_requirements` to serialized runnables.
=> FI-4107: Serialize runnable requirement ids

lib/inferno/dsl/must_support_assessment.rb, spec/fixtures/metadata/us_core_observation_adi_documentation_v800.yml, spec/inferno/dsl/must_support_assessment_spec.rb
This PR address FI-4167 US Core Observation ADI Documentation Profile MustSupport unit test failed
The root cause is that US Core Observation ADI Documentation Profile marked a extension.value[x] as MustSupport. Inferno Core's must_support_assessment only assess MustSupport using extension.url not extension.value
What's changed:
Add logic to verify that a must support extension has a must support value[x]
=> FI-4167 Support MustSupport element in extension

docs/swagger.yml, lib/inferno/apps/web/serializers/requirement.rb
This branch adds the `not_tested_reason` and `not_tested_details` fields to the requirements in the JSON API.
=> FI-4172: Add not-tested requirement fields to JSON API

dev_suites/dev_requirements/requirements/sample_requirements.csv, lib/inferno/entities/requirement.rb, lib/inferno/repositories/requirements.rb, spec/inferno/entities/requirement_spec.rb
This branch allows subrequirements to be defined with `requirement-set#actor`.
Add the pdex and bulk data requirement conversion branches to the Gemfile, require the pdex test kit in the demo suite. In the pdex branch, if you change the requirement set in the server suite from:
```ruby
identifier: 'hl7.fhir.uv.bulkdata_2.0.0',
title: 'Bulk Data Access IG',
actor: 'Server'
```
to:
```ruby
identifier: 'hl7.fhir.uv.bulkdata_2.0.0',
title: 'Bulk Data Access IG',
actor: 'Server',
requirements: 'referenced'
```
you will see the bulk data requirements in the requirements ui for the suite.
=> FI-4168: Support actor subrequirements

lib/inferno/repositories/requirements.rb
This branch handles errors when loading requirements.
I used the requirements update branches on pdex and bulk data to test this. On `main`, the errors from the requirements will prevent inferno from starting. On this branch, the UI will still load, but the suite requirements UI won't be displayed for PDEX. Changing the `Actor` heading to `Actors` in the CSVs on those test kit branches will allow the suite requirements UI to be displayed even though some errors are still displayed while loading.
=> FI-4177: Add error handling to requirements loading

lib/inferno/apps/cli/requirements_coverage_checker.rb
This branch prevents the requirements coverage check command from failing when a suite declares requirements which aren't included in its requirement sets.
=> FI-4181: Make unmatched requirement ids a warning rather than an error

lib/inferno/entities/requirement.rb, spec/inferno/entities/requirement_spec.rb
This branch updates the requirements handling to support non-numeric requirement ids.
=> FI-4169: Support non-numeric requirement ids

client/src/components/App/__mocked_data__/mockData.ts, client/src/models/testSuiteModels.ts, docs/swagger.yml, lib/inferno/apps/cli/requirements.rb, lib/inferno/apps/cli/requirements_exporter.rb, lib/inferno/apps/web/serializers/requirement.rb, lib/inferno/entities/requirement.rb, lib/inferno/repositories/requirements.rb, spec/inferno/entities/requirement_spec.rb, spec/inferno/repositories/requirements_spec.rb, spec/requests/requirements_spec.rb
This branch:
- loads requirements into the repository after export so that subrequirements can be properly evaluated when performing an export
- lazily loads subrequirements to avoid issues with the order in which requirement sets are loaded
- renames `sub_requirement` to `subrequirement` throughout the code
=> FI-4191: Fix requirements loading

dev_suites/dev_requirements/requirements_suite.rb, lib/inferno/apps/web/serializers/requirements_filtering_extractor.rb, lib/inferno/apps/web/serializers/test.rb, lib/inferno/apps/web/serializers/test_group.rb, lib/inferno/apps/web/serializers/test_session.rb, lib/inferno/apps/web/serializers/test_suite.rb, spec/fixtures/requirements/ig_requirements_requirements_coverage.csv, spec/inferno/web/serializers/test_group_spec.rb, spec/inferno/web/serializers/test_spec.rb, spec/inferno/web/serializers/test_suite_spec.rb
This branch updates the suite/group/test serializers to filter `verifies_requirements` to only include the requirements which are part of the requirement sets defined in the suite.
On prod:
On this branch:
You can follow the instructions in the Gemfile to load up g10 and verify that the requirements are filtered.
=> FI-4242: Filter runnable requirements in serializers

publish.sh
Some new js files have been added to `lib/inferno/public/`, so the gem publishing script needs to be updated so that it doesn't delete them.
=> Fix publish script

lib/inferno/apps/web/router.rb
Use a temporary rather than permanent redirect and add cache-control header for the test kit page to prevent the browser from caching the redirect.
=> FI-4252: Use a temporary redirect for root test kit page
