- .codecov.yml
- .github/workflows/js.yml
- .github/workflows/ruby.yml
- .rubocop.yml
- Gemfile
- Gemfile.lock
- README.md
- spec/spec_helper.rb
This branch adds CI pipelines for testing, linting with ruby and js, as well as coverage reporting for ruby.
> FI-1245: Add CI Pipeline

- client/src/components/LandingPage/LandingPage.tsx
- client/src/components/LandingPage/__tests__/LandingPage.test.tsx
- package-lock.json
- package.json
This PR makes it so the client doesn't spam the server for test suites when the server doesn't have any.
> fi-1252-don't spam server when no test suites

- client/src/api/infernoApiService.ts
- client/src/components/Header/Header.tsx
- client/src/components/TestSuite/TestRunProgressBar/TestRunProgressBar.tsx
- client/src/components/TestSuite/TestSession.tsx
- client/src/components/TestSuite/TestSessionWrapper.tsx
- client/src/models/testSuiteModels.ts
- docs/swagger.yml
- lib/inferno/apps/web/controllers/test_runs/show.rb
- lib/inferno/apps/web/controllers/test_sessions/last_test_run.rb
- lib/inferno/apps/web/controllers/test_sessions/results/index.rb
- lib/inferno/apps/web/router.rb
- lib/inferno/apps/web/serializers/test_group.rb
- lib/inferno/apps/web/serializers/test_run.rb
- lib/inferno/apps/web/serializers/test_session.rb
- lib/inferno/apps/web/serializers/test_suite.rb
- lib/inferno/dsl/runnable.rb
- lib/inferno/entities/test.rb
- lib/inferno/entities/test_run.rb
- lib/inferno/entities/test_session.rb
- lib/inferno/repositories/test_runs.rb
- spec/inferno/dsl/runnable_spec.rb
- spec/requests/test_sessions_spec.rb
This branch updates the UI to poll for results while tests are running and show a progress bar, along with the associated backend improvements to support this.
> FI-1273: Async UI updates

- client/src/components/App/App.tsx
- client/src/components/Header/Header.tsx
- client/src/components/Header/styles.tsx
- client/src/components/LandingPage/LandingPage.tsx
- client/src/components/TestSuite/TestSession.tsx
- client/src/components/TestSuite/TestSuiteDetails/TestSuiteDetailsPanel.tsx
- client/src/components/TestSuite/TestSuiteDetails/styles.tsx
- client/src/components/TestSuite/TestSuiteTree/TestSuiteTree.tsx
- client/src/components/TestSuite/TestSuiteTree/styles.tsx
- client/src/components/TestSuite/styles.tsx
- client/src/index.css
Updates the UI to use conventional components; namely, the header now uses AppBar and the side TreeView is now held in a Drawer. 
Note: The AppBar z-index must be forced, there may be another workaround for this but it would require more investigation.
> Navigation drawer

- lib/inferno/dsl/fhir_validation.rb
- spec/inferno/dsl/fhir_validation_spec.rb
This branch adds support for adding extra validation functions to a FHIR Validator, and adds documentation to the validation module.
> FI-1381: Support additional validation functions

- lib/inferno/db/migrations/001_create_initial_structure.rb
- lib/inferno/db/schema.rb
SQLite seems to be fine with this error, but postgres isn't.
> Fix bad migration

- client/src/components/Header/Header.tsx
- client/src/components/Header/__tests__/Header.test.tsx
- client/src/components/TestSuite/TestRunButton/TestRunButton.tsx
- client/src/components/TestSuite/TestSuiteDetails/ResultIcon.tsx
- client/src/components/TestSuite/TestSuiteDetails/TestListItem/MessagesList.tsx
- client/src/components/TestSuite/TestSuiteDetails/TestListItem/RequestsList.tsx
- client/src/components/TestSuite/TestSuiteDetails/TestListItem/TestListItem.tsx
- client/src/components/TestSuite/TestSuiteDetails/TestListItem/styles.tsx
- client/src/components/TestSuite/TestSuiteTree/CondensedResultIcon.tsx
- client/src/components/_common/TreeItem.tsx
Fixes a number of minor UI bugs/improves UI, including: 
- Fixing tree width
- Replacing numerical notification chips with badges
- Converting logo from button to link
- Adding purple errors
- Updating requests and messages table visuals
- Adding tooltips to request URLs
> Minor UI changes

- client/src/components/InputsModal/InputsModal.tsx
- client/src/components/InputsModal/InputsRadioGroup.tsx
- client/src/components/InputsModal/__tests__/InputModal.test.tsx
- client/src/components/InputsModal/styles.tsx
- client/src/models/testSuiteModels.ts
- dev_suites/dev_demo_ig_stu1/groups/demo_group.rb
- docs/swagger.yml
- docs/writing-tests/test-inputs-outputs.md
- lib/inferno/dsl/runnable.rb
Adds option to include radio button inputs in the inputs modal. Also updates the demo group tests.
> FI-1390 radio button input

- client/src/components/InputsModal/InputOAuthCredentials.tsx
- client/src/components/InputsModal/InputTextArea.tsx
- client/src/components/InputsModal/InputTextField.tsx
- client/src/components/InputsModal/InputsModal.tsx
- client/src/components/InputsModal/InputsRadioGroup.tsx
- client/src/components/InputsModal/styles.tsx
- client/src/components/TestSuite/TestSession.tsx
- client/src/components/TestSuite/TestSuiteDetails/TestListItem/RequestsList.tsx
- client/src/components/TestSuite/TestSuiteUtilities.tsx
- client/src/models/testSuiteModels.ts
I'm not thrilled about the required input management here but it at least resolves the issues raised in the last PR. We may want to reconsider the way nested objects are passed from the tests in anticipation of other, similar JSON handling issues. I will probably follow-up with a better solution if I can get one working.
This should update the following:
- Corrected, clearer labels for input fields, including required labels
- Submit button is disabling on empty required inputs
- Some other refactoring to clarify code
> FI-1417-refresh-UI

- lib/inferno/dsl/oauth_credentials.rb
- lib/inferno/repositories/session_data.rb
Ensure that `JSON.parse` doesn't try to parse `nil`.
> FI-1439: Fix cancel error

- client/src/components/Footer/Footer.tsx
- client/src/components/Footer/styles.tsx
- client/src/components/Header/Header.tsx
- client/src/components/Header/styles.tsx
- client/src/components/InputsModal/InputsModal.tsx
- client/src/components/LandingPage/styles.tsx
- client/src/components/TestSuite/TestRunButton/TestRunButton.tsx
- client/src/components/TestSuite/TestRunProgressBar/TestRunProgressBar.tsx
- client/src/components/TestSuite/TestRunProgressBar/styles.tsx
- client/src/components/TestSuite/TestSessionWrapper.tsx
- client/src/components/TestSuite/TestSuiteDetails/TestGroupCard.tsx
- client/src/components/TestSuite/TestSuiteDetails/TestListItem/TestListItem.tsx
- client/src/components/TestSuite/TestSuiteDetails/styles.tsx
- client/src/components/TestSuite/TestSuiteTree/TestGroupTreeItem.tsx
- client/src/components/TestSuite/TestSuiteTree/TestSuiteTree.tsx
- client/src/components/TestSuite/TestSuiteTree/styles.tsx
- client/src/components/TestSuite/styles.tsx
- client/src/components/_common/TreeItem.tsx
- client/src/styles/theme.tsx
Updates styles for key components, notably the header, footer, tree drawer, and progress bar.
> Clean up UI

- Gemfile
- config/presets/g10_certification_preset.json
- config/presets/smart_preset.json
- config/presets/us_core_preset.json
- dev_suites/dev_demo_ig_stu1/demo_suite.rb
This branch adds presets for the US Core, SMART, and g10 test kits for easier testing. It also updates the instructions for running the g10 test kit.
> FI-1420: Add presets

- lib/inferno/entities/test.rb
- spec/inferno/dsl/test_creation_spec.rb
> Revert id format

- client/src/components/Footer/Footer.tsx
- client/src/components/Footer/styles.tsx
- client/src/components/Header/Header.tsx
- client/src/components/PresetsModal/PresetsModal.tsx
- client/src/components/TestSuite/TestRunButton/TestRunButton.tsx
- client/src/components/TestSuite/TestSuiteDetails/TestGroupListItem.tsx
- client/src/components/TestSuite/TestSuiteDetails/TestListItem/RequestsList.tsx
- client/src/components/TestSuite/TestSuiteDetails/TestListItem/TestListItem.tsx
- client/src/components/TestSuite/TestSuiteTree/styles.tsx
Fixes some console errors and small UI inconsistencies
> ui-cleanup

- client/src/components/Header/Header.tsx
- client/src/components/RequestDetailModal/RequestDetailModal.tsx
- client/src/components/RequestDetailModal/styles.tsx
1. Fixes `New Session` button home routing bug
2. Fixes doubled tooltip on request modal bug
3. Updates request modal to use MUI flexbox props
> Fi 1512 fix routing

- client/src/components/Header/styles.tsx
- client/src/components/TestSuite/TestSession.tsx
- client/src/components/TestSuite/styles.tsx
- lib/inferno/apps/web/index.html.erb
Essentially a fix for unintended changes resulting from adding the banner.
> FI 1526: Position Header and Drawer

- client/src/components/Footer/styles.tsx
- client/src/components/TestSuite/styles.tsx
Fixes bug where print view would only print 1 page of the report.
> fix report view single page bug

- docs/concepts.md
- docs/distributing-tests.md
- docs/overview.md
- docs/writing-tests/making-requests.md
Just a couple things I noticed looking through the docs
> Random typo fixes

- client/src/components/Footer/Footer.tsx
- client/src/components/InputsModal/InputsModal.tsx
- client/src/components/TestSuite/TestRunButton/TestRunButton.tsx
- client/src/components/TestSuite/TestSession.tsx
- client/src/components/TestSuite/TestSuiteDetails/TestGroupCard.tsx
- client/src/components/TestSuite/TestSuiteDetails/TestGroupListItem.tsx
- client/src/components/TestSuite/TestSuiteDetails/TestListItem/InputOutputsList.tsx
- client/src/components/TestSuite/TestSuiteDetails/TestListItem/MessagesList.tsx
- client/src/components/TestSuite/TestSuiteDetails/TestListItem/RequestsList.tsx
- client/src/components/TestSuite/TestSuiteDetails/TestListItem/TestListItem.tsx
- client/src/components/TestSuite/TestSuiteDetails/TestListItem/styles.tsx
- client/src/components/TestSuite/styles.tsx
Part 1 of the Deque Axe tool a11y review:
- Adds landmark components
- Fixes many aria label inconsistencies
- Nests `li` components in lists
- Adds a workaround for input modal missing h1
> a11y-review-1

- lib/inferno/apps/web/index.html.erb
* allow IE11 to use its highest possible compat mode
* should be a harmless meta tag to anything else
* related to onc-healthit/inferno-program#437
> Add IE meta tag

- CHANGELOG.md
- Gemfile.lock
- lib/inferno/version.rb
Small release to get the fix necessary for CodeSpaces into the gem, as well as more a11y updates.
> Release v0.3.3

- docs/deployment/database.md
- docs/deployment/host.md
- docs/deployment/index.md
- docs/deployment/security.md
- docs/deployment/ssl.md
This branch adds deployment documentation. In particular, it covers SSRF protection, database configuration, ssl configuration, and hostname/base path configuration.
> FI-1588: Add deployment documentation

- lib/inferno/dsl/fhir_validation.rb
- spec/inferno/dsl/assertions_spec.rb
- spec/inferno/dsl/fhir_validation_spec.rb
WIP until unit tests completed.
> FI-540: Add Resource/Id to error message

- CHANGELOG.md
- Gemfile.lock
- lib/inferno/version.rb
Release w/suite options improvements.
> Release 0.3.8

- .github/workflows/ruby.yml
Trying to debug why #245 got stuck.
Watch the Checks tab.
> Update checkout github action

- client/src/components/LandingPage/LandingPage.tsx
Sorts suites on landing page by title alphabetically
Confirm that suites list is sorted
> sort suites alphabetically

- CHANGELOG.md
- Gemfile.lock
- lib/inferno/db/migrations/008_remove_timestamps.rb
- lib/inferno/db/schema.rb
- lib/inferno/entities/header.rb
- lib/inferno/entities/message.rb
- lib/inferno/repositories/headers.rb
- lib/inferno/repositories/messages.rb
- lib/inferno/version.rb
These changes have been released on top of 0.4.2.
> FI-1788: Remove timestamps

- CHANGELOG.md
- Gemfile.lock
- inferno_core.gemspec
- lib/inferno/version.rb
Update hanami-router to solve issue with inputs containing `%` (see https://github.com/onc-healthit/onc-certification-g10-test-kit/issues/338)
> FI-1804: Update router

- lib/inferno/dsl/fhir_client.rb
- spec/inferno/dsl/fhir_client_spec.rb
This was requested in zulip: https://chat.fhir.org/#narrow/stream/179309-inferno/topic/Creating.20a.20test.20kit.20that.20includes.20put.20and.20posts
> FI-1809: Add DSL support for FHIR create interaction

- Gemfile.lock
- docs/Gemfile.lock
> Update ruby dependencies

- Gemfile.lock
- inferno_core.gemspec
- lib/inferno/repositories/test_sessions.rb
This branch updates sessions to use the same style of short ids that we used in program.
Create a new session and it will have a shorter id.
> FI-1893: Shorten session ids

- docs/advanced-test-features/scratch.md
- docs/getting-started.md
- docs/writing-tests/assertions-and-results.md
- docs/writing-tests/fhir-validation.md
- docs/writing-tests/making-requests.md
- docs/writing-tests/test-inputs-outputs.md
- lib/inferno/dsl/assertions.rb
- spec/inferno/dsl/assertions_spec.rb
Update the documentation based on feedback.
> FI-1910: Update documentation

- docs/overview.md
Added more content to the overview based on some of the content provided in the inferno-core README.
> Update to overview.

- docs/index.md
- docs/overview.md
Very minor issues that I just noticed.
> Fix minor doc typos.

- client/src/components/SuiteOptionsPage/SuiteOptionsPage.tsx
- client/src/components/SuiteOptionsPage/styles.tsx
Fixes an overflow bug introduced in FI-1975. Moved the title to prevent overflow bugs.
https://github.com/inferno-framework/inferno-core/assets/11209247/8af6f68b-b2e1-4759-8f1a-2ff6f77c3ffc
> FI-1979 Small adjustment to flex model on suite options

- docs/advanced-test-features/serving-http-requests.md
Fixed outdated and incorrect information on the Advanced Test Features Page of Inferno Framework Documentation
> FI-2070-Inferno Framework Documentation Advanced Test Features Information Fix

- CHANGELOG.md
- Gemfile.lock
- lib/inferno/version.rb
Release notes:
* FI-2347: Set radio default input by @AlyssaWang in https://github.com/inferno-framework/inferno-core/pull/416
> Inferno Core Release 0.4.24

- CHANGELOG.md
- Gemfile.lock
- lib/inferno/version.rb
* FI-2270: Migrate FI-1990, fix flicker by @AlyssaWang in https://github.com/inferno-framework/inferno-core/pull/409
* FI-2383: Force page reroute in header by @AlyssaWang in https://github.com/inferno-framework/inferno-core/pull/419
* FI-2236: Support arbitrary fields in HL7 validator cliContext by @dehall in https://github.com/inferno-framework/inferno-core/pull/413
> Release 0425

- spec/inferno/apps/cli/main_spec.rb
It somehow passed GitHub actions but fails locally.
`bundle exec rake spec` on local machine, probably.
> Inferno Version RSpec Patch

- docs/available-test-kits.md
Make sure all references to 2015 Edition were replaced.
> FI-2450: Change "2015 Edition Cures Update" to "ONC Certification Update"

- lib/inferno/apps/web/controllers/test_sessions/create.rb
- spec/request_helper.rb
- spec/requests/test_sessions_spec.rb
This reverts commit 5c35cf6c3bf818d2540bfa8a4318df3ad018df45.
> FI-2487: Revert "FI-2318 Allow for form data at session create endpoint (#429)"

- client/src/components/PresetsSelector/__tests__/PresetsSelector.test.tsx
- client/src/components/Skeletons/TestSessionSkeleton.tsx
- client/src/components/TestSuite/TestRunButton/TestRunButton.tsx
- client/src/components/TestSuite/TestRunButton/__mocked_data__/mockData.ts
- client/src/components/TestSuite/TestRunButton/__tests__/TestRunButton.test.tsx
- client/src/components/TestSuite/TestSession.tsx
- client/src/components/TestSuite/TestSuiteDetails/TestGroupCard.tsx
- client/src/components/TestSuite/TestSuiteTree/TestSuiteTree.tsx
- client/src/components/_common/CustomTreeItem.tsx
- client/src/components/_common/__mocked_data__/mockData.ts
- client/src/components/_common/__tests__/TreeItem.test.tsx
- package-lock.json
- package.json
Shows text 'Run' button on mobile instead of icon button and removes extra padding.
Also updates packages and tests, with minor changes to tree components.
Check that different screen widths don't cause too much bad overflow.
> FI-2485: Update mobile main test run button appearance

- client/src/components/App/App.tsx
- client/src/components/TestSuite/TestRunButton/TestRunButton.tsx
- client/src/components/TestSuite/TestSession.tsx
- client/src/components/TestSuite/TestSuiteUtilities.tsx
- client/src/models/testSuiteModels.ts
- client/src/store/app.ts
- client/src/store/devtools.ts
- client/src/store/testSession.ts
- package-lock.json
- package.json
Test run results should now be specific to each run rather than overlapping result icons/visuals.
In (g)(10), run the Multi-Patient API tests. Open another tab and run the Standalone Patient App tests against the reference server. Follow the redirect link when prompted. When the site returns to Inferno Core, the pending icons should not appear on the Multi-Patient API tests.
> FI-2490: Fix multiple test run results overlapping

- CHANGELOG.md
- Gemfile.lock
- lib/inferno/version.rb
* have gemspec include dotfiles from lib/inferno/apps/cli/templates/ by @Shaumik-Ashraf in https://github.com/inferno-framework/inferno-core/pull/470
> Release 0433

- CHANGELOG.md
- Gemfile.lock
- lib/inferno/version.rb
* Include JSON files in gem package by @vanessuniq in https://github.com/inferno-framework/inferno-core/pull/524
> Inferno Core v0.4.41 Release

- CHANGELOG.md
- Gemfile.lock
- lib/inferno/version.rb
* FI-2887 Remove banner info from readme because that belongs in the docs site. by @arscan in https://github.com/inferno-framework/inferno-core/pull/527
* FI-3112: Fixed JWKS Template Path Used in Unit Tests by @vanessuniq in https://github.com/inferno-framework/inferno-core/pull/526
> Release 0442

- CHANGELOG.md
- Gemfile.lock
- lib/inferno/version.rb
* patch undefined method for nil on validator 500 response by @Shaumik-Ashraf in https://github.com/inferno-framework/inferno-core/pull/530
* FI-3172: Fix validator sessions by @Jammjammjamm in https://github.com/inferno-framework/inferno-core/pull/531
> Release 0443

- CHANGELOG.md
- Gemfile.lock
- lib/inferno/version.rb
* FI-2937 inferno execute by @Shaumik-Ashraf in https://github.com/inferno-framework/inferno-core/pull/517
* FI-3104: Update React + other packages by @AlyssaWang in https://github.com/inferno-framework/inferno-core/pull/529
* FI-3188: Update documentation on cli_context options. by @arscan in https://github.com/inferno-framework/inferno-core/pull/535
* cli git ignore .gem by @rpassas in https://github.com/inferno-framework/inferno-core/pull/534
* FI-3076: Add FHIRPath Service to Template by @vanessuniq in https://github.com/inferno-framework/inferno-core/pull/532
* FI-3275 debug: inferno execute input validation by @Shaumik-Ashraf in https://github.com/inferno-framework/inferno-core/pull/542
* FI-3193 Add instruction to build Ruby Docs by @mrnosal in …
> Release v0.4.44

- .github/workflows/docs.yml
This will fix the failing CI on main
> Change ruby to 3.3.6 in docs.yml

- lib/inferno/apps/cli/templates/.github/workflows/ruby.yml
See inferno-framework/inferno-template#33
> Set Ruby to 3.3.6 in Thor CI Template

- lib/inferno/apps/cli/templates/Dockerfile.tt
See [this comment](https://github.com/inferno-framework/inferno-template/pull/33#discussion_r1953125265) and file diff.
1. checkout branch
2. `bundle exec ./bin/inferno new try_new_docker`
3. `cd try_new_docker`
4. `./setup.sh && ./run.sh`
5. Go to <http://127.0.0.1:80> and the default test suite should appear and work. (However hapi.fhir.org is down this moment so don't use that server to test it.)
> Fix Thor Template Dockerfile

- lib/inferno/apps/cli/templates/.env.development
- lib/inferno/apps/cli/templates/.env.production
This branch adds INFERNO_HOST to template.
> FI-3473: Add INFERNO_HOST to Template

- lib/inferno/dsl/fhir_resource_validation.rb
- lib/inferno/dsl/fhirpath_evaluation.rb
- spec/inferno/dsl/fhir_resource_validation_spec.rb
- spec/inferno/dsl/fhirpath_evaluation_spec.rb
For #651.
Add more error handling paths to where the validation request happens. There is another place where a similar request happens. If this an acceptable idea I can change that there too and update this PR. This also should have an effect on the UI message because it seems to use the String from the raise.
I only tested this through rspec. It's been a while since I've booted a pre-release gem locally.
> Narrower error handling on validator request

- README.md
> FI-4235: Add link to validator in readme

- lib/inferno/dsl.rb
- lib/inferno/dsl/fhir_resource_navigation.rb
The `FHIRResourceNavigation` wasn't being automatically included in tests, but it should be.
> FI-4258: Update fhir resource navigation
